import type { Availability } from '@payload-types'

type CreateAvailability = Omit<
  Availability,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const inactiveAvailability: CreateAvailability[] = [
  // Inactive Properties (Parent)
  {
    title: 'Inactive Properties',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'inactive-properties',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b440b',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
    ],
    _status: 'published',
  },
  // Occupied (Child of Inactive Properties)
  {
    title: 'Occupied',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'occupied',
    slugLock: true,
    parent: 1,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b441c',
        doc: 102,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b7de9a1e4304421b441d',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
    ],
    _status: 'published',
  },
  // Rented (Child of Occupied)
  {
    title: 'Rented',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'rented',
    slugLock: true,
    parent: 2,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b442e',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b442f',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4430',
        doc: 104,
        url: '/inactive-properties/occupied/rented',
        label: 'Rented',
      },
    ],
    _status: 'published',
  },
  // Tenant Moved In (Child of Rented)
  {
    title: 'Tenant Moved In',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:50.276Z',
    slug: 'tenant-moved-in',
    slugLock: true,
    parent: 3,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4441',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4442',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4443',
        doc: 104,
        url: '/inactive-properties/occupied/rented',
        label: 'Rented',
      },
      {
        id: '67b0b8449a1e4304421b4444',
        doc: 105,
        url: '/inactive-properties/occupied/rented/tenant-moved-in',
        label: 'Tenant Moved In',
      },
    ],
    _status: 'published',
  },
  // Lease Active (Child of Rented)
  {
    title: 'Lease Active',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:50.276Z',
    slug: 'lease-active',
    slugLock: true,
    parent: 3,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4451',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4452',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4453',
        doc: 104,
        url: '/inactive-properties/occupied/rented',
        label: 'Rented',
      },
      {
        id: '67b0b8449a1e4304421b4454',
        doc: 106,
        url: '/inactive-properties/occupied/rented/lease-active',
        label: 'Lease Active',
      },
    ],
    _status: 'published',
  },
  // Pending Move-in Date (Child of Rented)
  {
    title: 'Pending Move-in Date',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:50.276Z',
    slug: 'pending-move-in-date',
    slugLock: true,
    parent: 3,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4461',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4462',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4463',
        doc: 104,
        url: '/inactive-properties/occupied/rented',
        label: 'Rented',
      },
      {
        id: '67b0b8449a1e4304421b4464',
        doc: 107,
        url: '/inactive-properties/occupied/rented/pending-move-in-date',
        label: 'Pending Move-in Date',
      },
    ],
    _status: 'published',
  },
  // Sold (Child of Occupied)
  {
    title: 'Sold',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:50.276Z',
    slug: 'sold',
    slugLock: true,
    parent: 2,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4471',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4472',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4473',
        doc: 108,
        url: '/inactive-properties/occupied/sold',
        label: 'Sold',
      },
    ],
    _status: 'published',
  },
  // Ownership Transferred (Child of Sold)
  {
    title: 'Ownership Transferred',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:50.276Z',
    slug: 'ownership-transferred',
    slugLock: true,
    parent: 8,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4481',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4482',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4483',
        doc: 108,
        url: '/inactive-properties/occupied/sold',
        label: 'Sold',
      },
      {
        id: '67b0b8449a1e4304421b4484',
        doc: 109,
        url: '/inactive-properties/occupied/sold/ownership-transferred',
        label: 'Ownership Transferred',
      },
    ],
    _status: 'published',
  },
  // Transfer in Progress (Child of Sold)
  {
    title: 'Transfer in Progress',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:57:50.276Z',
    slug: 'transfer-in-progress',
    slugLock: true,
    parent: 8,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4491',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4492',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b4493',
        doc: 108,
        url: '/inactive-properties/occupied/sold',
        label: 'Sold',
      },
      {
        id: '67b0b8449a1e4304421b4494',
        doc: 110,
        url: '/inactive-properties/occupied/sold/transfer-in-progress',
        label: 'Transfer in Progress',
      },
    ],
    _status: 'published',
  },
  // Final Documentation (Child of Sold)
  {
    title: 'Final Documentation',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:58:50.276Z',
    slug: 'final-documentation',
    slugLock: true,
    parent: 8,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b44a1',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b44a2',
        doc: 103,
        url: '/inactive-properties/occupied',
        label: 'Occupied',
      },
      {
        id: '67b0b8449a1e4304421b44a3',
        doc: 108,
        url: '/inactive-properties/occupied/sold',
        label: 'Sold',
      },
      {
        id: '67b0b8449a1e4304421b44a4',
        doc: 111,
        url: '/inactive-properties/occupied/sold/final-documentation',
        label: 'Final Documentation',
      },
    ],
    _status: 'published',
  },
  // On Hold (Child of Inactive Properties)
  {
    title: 'On Hold',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:50.276Z',
    slug: 'on-hold',
    slugLock: true,
    parent: 1,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b44b1',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b44b2',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
    ],
    _status: 'published',
  },
  // Maintenance (Child of On Hold)
  {
    title: 'Maintenance',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:50.276Z',
    slug: 'maintenance',
    slugLock: true,
    parent: 112,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b44c1',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b44c2',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b44c3',
        doc: 113,
        url: '/inactive-properties/on-hold/maintenance',
        label: 'Maintenance',
      },
    ],
    _status: 'published',
  },
  // Under Renovation (Child of Maintenance)
  {
    title: 'Under Renovation',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:01:50.276Z',
    slug: 'under-renovation',
    slugLock: true,
    parent: 113,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b44d1',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b44d2',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b44d3',
        doc: 113,
        url: '/inactive-properties/on-hold/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0b8449a1e4304421b44d4',
        doc: 114,
        url: '/inactive-properties/on-hold/maintenance/under-renovation',
        label: 'Under Renovation',
      },
    ],
    _status: 'published',
  },
  // Repairs in Progress (Child of Maintenance)
  {
    title: 'Repairs in Progress',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:02:50.276Z',
    slug: 'repairs-in-progress',
    slugLock: true,
    parent: 113,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b44e1',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b44e2',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b44e3',
        doc: 113,
        url: '/inactive-properties/on-hold/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0b8449a1e4304421b44e4',
        doc: 115,
        url: '/inactive-properties/on-hold/maintenance/repairs-in-progress',
        label: 'Repairs in Progress',
      },
    ],
    _status: 'published',
  },
  // Inspection Pending (Child of Maintenance)
  {
    title: 'Inspection Pending',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:03:50.276Z',
    slug: 'inspection-pending',
    slugLock: true,
    parent: 113,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b44f1',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b44f2',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b44f3',
        doc: 113,
        url: '/inactive-properties/on-hold/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0b8449a1e4304421b44f4',
        doc: 116,
        url: '/inactive-properties/on-hold/maintenance/inspection-pending',
        label: 'Inspection Pending',
      },
    ],
    _status: 'published',
  },
  // Administrative (Child of On Hold)
  {
    title: 'Administrative',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:04:50.276Z',
    slug: 'administrative',
    slugLock: true,
    parent: 112,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4501',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4502',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4503',
        doc: 117,
        url: '/inactive-properties/on-hold/administrative',
        label: 'Administrative',
      },
    ],
    _status: 'published',
  },
  // Legal Review (Child of Administrative)
  {
    title: 'Legal Review',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:05:50.276Z',
    slug: 'legal-review',
    slugLock: true,
    parent: 117,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4511',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4512',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4513',
        doc: 117,
        url: '/inactive-properties/on-hold/administrative',
        label: 'Administrative',
      },
      {
        id: '67b0b8449a1e4304421b4514',
        doc: 118,
        url: '/inactive-properties/on-hold/administrative/legal-review',
        label: 'Legal Review',
      },
    ],
    _status: 'published',
  },
  // Document Update (Child of Administrative)
  {
    title: 'Document Update',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:06:50.276Z',
    slug: 'document-update',
    slugLock: true,
    parent: 117,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4521',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4522',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4523',
        doc: 117,
        url: '/inactive-properties/on-hold/administrative',
        label: 'Administrative',
      },
      {
        id: '67b0b8449a1e4304421b4524',
        doc: 119,
        url: '/inactive-properties/on-hold/administrative/document-update',
        label: 'Document Update',
      },
    ],
    _status: 'published',
  },
  // Ownership Verification (Child of Administrative)
  {
    title: 'Ownership Verification',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:07:50.276Z',
    slug: 'ownership-verification',
    slugLock: true,
    parent: 117,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4531',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4532',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4533',
        doc: 117,
        url: '/inactive-properties/on-hold/administrative',
        label: 'Administrative',
      },
      {
        id: '67b0b8449a1e4304421b4534',
        doc: 120,
        url: '/inactive-properties/on-hold/administrative/ownership-verification',
        label: 'Ownership Verification',
      },
    ],
    _status: 'published',
  },
  // Market Strategy (Child of On Hold)
  {
    title: 'Market Strategy',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:08:50.276Z',
    slug: 'market-strategy',
    slugLock: true,
    parent: 112,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4541',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4542',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4543',
        doc: 121,
        url: '/inactive-properties/on-hold/market-strategy',
        label: 'Market Strategy',
      },
    ],
    _status: 'published',
  },
  // Temporarily Withdrawn (Child of Market Strategy)
  {
    title: 'Temporarily Withdrawn',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:09:50.276Z',
    slug: 'temporarily-withdrawn',
    slugLock: true,
    parent: 121,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4551',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4552',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4553',
        doc: 121,
        url: '/inactive-properties/on-hold/market-strategy',
        label: 'Market Strategy',
      },
      {
        id: '67b0b8449a1e4304421b4554',
        doc: 122,
        url: '/inactive-properties/on-hold/market-strategy/temporarily-withdrawn',
        label: 'Temporarily Withdrawn',
      },
    ],
    _status: 'published',
  },
  // Price Reconsideration (Child of Market Strategy)
  {
    title: 'Price Reconsideration',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:10:50.276Z',
    slug: 'price-reconsideration',
    slugLock: true,
    parent: 121,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4561',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4562',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4563',
        doc: 121,
        url: '/inactive-properties/on-hold/market-strategy',
        label: 'Market Strategy',
      },
      {
        id: '67b0b8449a1e4304421b4564',
        doc: 123,
        url: '/inactive-properties/on-hold/market-strategy/price-reconsideration',
        label: 'Price Reconsideration',
      },
    ],
    _status: 'published',
  },
  // Marketing Refresh (Child of Market Strategy)
  {
    title: 'Marketing Refresh',
    allowInquiries: false,
    showInSearch: false,
    color: 'gray',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:11:50.276Z',
    slug: 'marketing-refresh',
    slugLock: true,
    parent: 121,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4571',
        doc: 101,
        url: '/inactive-properties',
        label: 'Inactive Properties',
      },
      {
        id: '67b0b8449a1e4304421b4572',
        doc: 112,
        url: '/inactive-properties/on-hold',
        label: 'On Hold',
      },
      {
        id: '67b0b8449a1e4304421b4573',
        doc: 121,
        url: '/inactive-properties/on-hold/market-strategy',
        label: 'Market Strategy',
      },
      {
        id: '67b0b8449a1e4304421b4574',
        doc: 124,
        url: '/inactive-properties/on-hold/market-strategy/marketing-refresh',
        label: 'Marketing Refresh',
      },
    ],
    _status: 'published',
  },
]
