import type { Availability } from '@payload-types'

type CreateAvailability = Omit<
  Availability,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const activeAvailability: CreateAvailability[] = [
  // Active Properties (Parent)
  {
    title: 'Active Properties',
    allowInquiries: true,
    showInSearch: true,
    color: 'green',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'active-properties',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b439b',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
    ],
    _status: 'published',
  },
  // Available (Child of Active Properties)
  {
    title: 'Available',
    allowInquiries: true,
    showInSearch: true,
    color: 'green',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'available',
    slugLock: true,
    parent: 1,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b43a0',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b7de9a1e4304421b43a1',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
    ],
    _status: 'published',
  },
  // New to Market (Child of Available)
  {
    title: 'New to Market',
    allowInquiries: true,
    showInSearch: true,
    color: 'green',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'new-to-market',
    slugLock: true,
    parent: 2,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43a7',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8449a1e4304421b43a8',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8449a1e4304421b43a9',
        doc: 3,
        url: '/active-properties/available/new-to-market',
        label: 'New to Market',
      },
    ],
    _status: 'published',
  },
  // Just Listed (Child of New to Market)
  {
    title: 'Just Listed',
    allowInquiries: true,
    showInSearch: true,
    color: 'green',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:08.351Z',
    slug: 'just-listed',
    slugLock: true,
    parent: 3,
    breadcrumbs: [
      {
        id: '67b0b8649a1e4304421b43ae',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8649a1e4304421b43af',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8649a1e4304421b43b0',
        doc: 3,
        url: '/active-properties/available/new-to-market',
        label: 'New to Market',
      },
      {
        id: '67b0b8649a1e4304421b43b1',
        doc: 4,
        url: '/active-properties/available/new-to-market/just-listed',
        label: 'Just Listed',
      },
    ],
    _status: 'published',
  },
  // Fresh Launch (Child of New to Market)
  {
    title: 'Fresh Launch',
    allowInquiries: true,
    showInSearch: true,
    color: 'green',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'fresh-launch',
    slugLock: true,
    parent: 3,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b43b5',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b87a9a1e4304421b43b6',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b87a9a1e4304421b43b7',
        doc: 3,
        url: '/active-properties/available/new-to-market',
        label: 'New to Market',
      },
      {
        id: '67b0b87a9a1e4304421b43b8',
        doc: 5,
        url: '/active-properties/available/new-to-market/fresh-launch',
        label: 'Fresh Launch',
      },
    ],
    _status: 'published',
  },
  // Pre-Launch Registration (Child of New to Market)
  {
    title: 'Pre-Launch Registration',
    allowInquiries: true,
    showInSearch: true,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'pre-launch-registration',
    slugLock: true,
    parent: 3,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43ba',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43bb',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43bc',
        doc: 3,
        url: '/active-properties/available/new-to-market',
        label: 'New to Market',
      },
      {
        id: '67b0b8899a1e4304421b43bd',
        doc: 6,
        url: '/active-properties/available/new-to-market/pre-launch-registration',
        label: 'Pre-Launch Registration',
      },
    ],
    _status: 'published',
  },
  // Back to Market (Child of Available)
  {
    title: 'Back to Market',
    allowInquiries: true,
    showInSearch: true,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'back-to-market',
    slugLock: true,
    parent: 2,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43be',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43bf',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43c0',
        doc: 7,
        url: '/active-properties/available/back-to-market',
        label: 'Back to Market',
      },
    ],
    _status: 'published',
  },
  // Re-Listed (Child of Back to Market)
  {
    title: 'Re-Listed',
    allowInquiries: true,
    showInSearch: true,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 're-listed',
    slugLock: true,
    parent: 7,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43c1',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43c2',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43c3',
        doc: 7,
        url: '/active-properties/available/back-to-market',
        label: 'Back to Market',
      },
      {
        id: '67b0b8899a1e4304421b43c4',
        doc: 8,
        url: '/active-properties/available/back-to-market/re-listed',
        label: 'Re-Listed',
      },
    ],
    _status: 'published',
  },
  // Price Adjusted (Child of Back to Market)
  {
    title: 'Price Adjusted',
    allowInquiries: true,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'price-adjusted',
    slugLock: true,
    parent: 7,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43c5',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43c6',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43c7',
        doc: 7,
        url: '/active-properties/available/back-to-market',
        label: 'Back to Market',
      },
      {
        id: '67b0b8899a1e4304421b43c8',
        doc: 9,
        url: '/active-properties/available/back-to-market/price-adjusted',
        label: 'Price Adjusted',
      },
    ],
    _status: 'published',
  },
  // Newly Renovated (Child of Back to Market)
  {
    title: 'Newly Renovated',
    allowInquiries: true,
    showInSearch: true,
    color: 'green',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'newly-renovated',
    slugLock: true,
    parent: 7,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43c9',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43ca',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43cb',
        doc: 7,
        url: '/active-properties/available/back-to-market',
        label: 'Back to Market',
      },
      {
        id: '67b0b8899a1e4304421b43cc',
        doc: 10,
        url: '/active-properties/available/back-to-market/newly-renovated',
        label: 'Newly Renovated',
      },
    ],
    _status: 'published',
  },
  // Featured (Child of Available)
  {
    title: 'Featured',
    allowInquiries: true,
    showInSearch: true,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'featured',
    slugLock: true,
    parent: 2,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43cd',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43ce',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43cf',
        doc: 11,
        url: '/active-properties/available/featured',
        label: 'Featured',
      },
    ],
    _status: 'published',
  },
  // Hot Deal (Child of Featured)
  {
    title: 'Hot Deal',
    allowInquiries: true,
    showInSearch: true,
    color: 'red',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'hot-deal',
    slugLock: true,
    parent: 11,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43d0',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43d1',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43d2',
        doc: 11,
        url: '/active-properties/available/featured',
        label: 'Featured',
      },
      {
        id: '67b0b8899a1e4304421b43d3',
        doc: 12,
        url: '/active-properties/available/featured/hot-deal',
        label: 'Hot Deal',
      },
    ],
    _status: 'published',
  },
  // Premium Listing (Child of Featured)
  {
    title: 'Premium Listing',
    allowInquiries: true,
    showInSearch: true,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'premium-listing',
    slugLock: true,
    parent: 11,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43d4',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43d5',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43d6',
        doc: 11,
        url: '/active-properties/available/featured',
        label: 'Featured',
      },
      {
        id: '67b0b8899a1e4304421b43d7',
        doc: 13,
        url: '/active-properties/available/featured/premium-listing',
        label: 'Premium Listing',
      },
    ],
    _status: 'published',
  },
  // Special Offer (Child of Featured)
  {
    title: 'Special Offer',
    allowInquiries: true,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'special-offer',
    slugLock: true,
    parent: 11,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43d8',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43d9',
        doc: 2,
        url: '/active-properties/available',
        label: 'Available',
      },
      {
        id: '67b0b8899a1e4304421b43da',
        doc: 11,
        url: '/active-properties/available/featured',
        label: 'Featured',
      },
      {
        id: '67b0b8899a1e4304421b43db',
        doc: 14,
        url: '/active-properties/available/featured/special-offer',
        label: 'Special Offer',
      },
    ],
    _status: 'published',
  },
  // Reserved (Child of Active Properties)
  {
    title: 'Reserved',
    allowInquiries: false,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'reserved',
    slugLock: true,
    parent: 1,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43dc',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43dd',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
    ],
    _status: 'published',
  },
  // Booking Stage (Child of Reserved)
  {
    title: 'Booking Stage',
    allowInquiries: false,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'booking-stage',
    slugLock: true,
    parent: 15,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43de',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43df',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43e0',
        doc: 16,
        url: '/active-properties/reserved/booking-stage',
        label: 'Booking Stage',
      },
    ],
    _status: 'published',
  },
  // Viewing Scheduled (Child of Booking Stage)
  {
    title: 'Viewing Scheduled',
    allowInquiries: false,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'viewing-scheduled',
    slugLock: true,
    parent: 16,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43e1',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43e2',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43e3',
        doc: 16,
        url: '/active-properties/reserved/booking-stage',
        label: 'Booking Stage',
      },
      {
        id: '67b0b8899a1e4304421b43e4',
        doc: 17,
        url: '/active-properties/reserved/booking-stage/viewing-scheduled',
        label: 'Viewing Scheduled',
      },
    ],
    _status: 'published',
  },
  // Offer Received (Child of Booking Stage)
  {
    title: 'Offer Received',
    allowInquiries: false,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'offer-received',
    slugLock: true,
    parent: 16,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43e5',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43e6',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43e7',
        doc: 16,
        url: '/active-properties/reserved/booking-stage',
        label: 'Booking Stage',
      },
      {
        id: '67b0b8899a1e4304421b43e8',
        doc: 18,
        url: '/active-properties/reserved/booking-stage/offer-received',
        label: 'Offer Received',
      },
    ],
    _status: 'published',
  },
  // Under Negotiation (Child of Booking Stage)
  {
    title: 'Under Negotiation',
    allowInquiries: false,
    showInSearch: true,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'under-negotiation',
    slugLock: true,
    parent: 16,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43e9',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43ea',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43eb',
        doc: 16,
        url: '/active-properties/reserved/booking-stage',
        label: 'Booking Stage',
      },
      {
        id: '67b0b8899a1e4304421b43ec',
        doc: 19,
        url: '/active-properties/reserved/booking-stage/under-negotiation',
        label: 'Under Negotiation',
      },
    ],
    _status: 'published',
  },
  // Processing (Child of Reserved)
  {
    title: 'Processing',
    allowInquiries: false,
    showInSearch: false,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'processing',
    slugLock: true,
    parent: 15,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43ed',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43ee',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43ef',
        doc: 20,
        url: '/active-properties/reserved/processing',
        label: 'Processing',
      },
    ],
    _status: 'published',
  },
  // Deposit Paid (Child of Processing)
  {
    title: 'Deposit Paid',
    allowInquiries: false,
    showInSearch: false,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'deposit-paid',
    slugLock: true,
    parent: 20,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43f0',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43f1',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43f2',
        doc: 20,
        url: '/active-properties/reserved/processing',
        label: 'Processing',
      },
      {
        id: '67b0b8899a1e4304421b43f3',
        doc: 21,
        url: '/active-properties/reserved/processing/deposit-paid',
        label: 'Deposit Paid',
      },
    ],
    _status: 'published',
  },
  // Paperwork in Progress (Child of Processing)
  {
    title: 'Paperwork in Progress',
    allowInquiries: false,
    showInSearch: false,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'paperwork-in-progress',
    slugLock: true,
    parent: 20,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43f4',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43f5',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43f6',
        doc: 20,
        url: '/active-properties/reserved/processing',
        label: 'Processing',
      },
      {
        id: '67b0b8899a1e4304421b43f7',
        doc: 22,
        url: '/active-properties/reserved/processing/paperwork-in-progress',
        label: 'Paperwork in Progress',
      },
    ],
    _status: 'published',
  },
  // Final Checks (Child of Processing)
  {
    title: 'Final Checks',
    allowInquiries: false,
    showInSearch: false,
    color: 'yellow',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'final-checks',
    slugLock: true,
    parent: 20,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43f8',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43f9',
        doc: 15,
        url: '/active-properties/reserved',
        label: 'Reserved',
      },
      {
        id: '67b0b8899a1e4304421b43fa',
        doc: 20,
        url: '/active-properties/reserved/processing',
        label: 'Processing',
      },
      {
        id: '67b0b8899a1e4304421b43fb',
        doc: 23,
        url: '/active-properties/reserved/processing/final-checks',
        label: 'Final Checks',
      },
    ],
    _status: 'published',
  },
  // Under Contract (Child of Active Properties)
  {
    title: 'Under Contract',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'under-contract',
    slugLock: true,
    parent: 1,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43fc',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43fd',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
    ],
    _status: 'published',
  },
  // Documentation (Child of Under Contract)
  {
    title: 'Documentation',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'documentation',
    slugLock: true,
    parent: 24,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43fe',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b43ff',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b4400',
        doc: 25,
        url: '/active-properties/under-contract/documentation',
        label: 'Documentation',
      },
    ],
    _status: 'published',
  },
  // Contracts Issued (Child of Documentation)
  {
    title: 'Contracts Issued',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'contracts-issued',
    slugLock: true,
    parent: 25,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4401',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b4402',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b4403',
        doc: 25,
        url: '/active-properties/under-contract/documentation',
        label: 'Documentation',
      },
      {
        id: '67b0b8899a1e4304421b4404',
        doc: 26,
        url: '/active-properties/under-contract/documentation/contracts-issued',
        label: 'Contracts Issued',
      },
    ],
    _status: 'published',
  },
  // Pending Signatures (Child of Documentation)
  {
    title: 'Pending Signatures',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'pending-signatures',
    slugLock: true,
    parent: 25,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4405',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b4406',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b4407',
        doc: 25,
        url: '/active-properties/under-contract/documentation',
        label: 'Documentation',
      },
      {
        id: '67b0b8899a1e4304421b4408',
        doc: 27,
        url: '/active-properties/under-contract/documentation/pending-signatures',
        label: 'Pending Signatures',
      },
    ],
    _status: 'published',
  },
  // Security Checks (Child of Documentation)
  {
    title: 'Security Checks',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'security-checks',
    slugLock: true,
    parent: 25,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4409',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b440a',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b440b',
        doc: 25,
        url: '/active-properties/under-contract/documentation',
        label: 'Documentation',
      },
      {
        id: '67b0b8899a1e4304421b440c',
        doc: 28,
        url: '/active-properties/under-contract/documentation/security-checks',
        label: 'Security Checks',
      },
    ],
    _status: 'published',
  },
  // Payment Process (Child of Under Contract)
  {
    title: 'Payment Process',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'payment-process',
    slugLock: true,
    parent: 24,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b440d',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b440e',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b440f',
        doc: 29,
        url: '/active-properties/under-contract/payment-process',
        label: 'Payment Process',
      },
    ],
    _status: 'published',
  },
  // Initial Payment Made (Child of Payment Process)
  {
    title: 'Initial Payment Made',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'initial-payment-made',
    slugLock: true,
    parent: 29,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4410',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b4411',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b4412',
        doc: 29,
        url: '/active-properties/under-contract/payment-process',
        label: 'Payment Process',
      },
      {
        id: '67b0b8899a1e4304421b4413',
        doc: 30,
        url: '/active-properties/under-contract/payment-process/initial-payment-made',
        label: 'Initial Payment Made',
      },
    ],
    _status: 'published',
  },
  // Awaiting Final Payment (Child of Payment Process)
  {
    title: 'Awaiting Final Payment',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'awaiting-final-payment',
    slugLock: true,
    parent: 29,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4414',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b4415',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b4416',
        doc: 29,
        url: '/active-properties/under-contract/payment-process',
        label: 'Payment Process',
      },
      {
        id: '67b0b8899a1e4304421b4417',
        doc: 31,
        url: '/active-properties/under-contract/payment-process/awaiting-final-payment',
        label: 'Awaiting Final Payment',
      },
    ],
    _status: 'published',
  },
  // Payment Plan Setup (Child of Payment Process)
  {
    title: 'Payment Plan Setup',
    allowInquiries: false,
    showInSearch: false,
    color: 'blue',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'payment-plan-setup',
    slugLock: true,
    parent: 29,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4418',
        doc: 1,
        url: '/active-properties',
        label: 'Active Properties',
      },
      {
        id: '67b0b8899a1e4304421b4419',
        doc: 24,
        url: '/active-properties/under-contract',
        label: 'Under Contract',
      },
      {
        id: '67b0b8899a1e4304421b441a',
        doc: 29,
        url: '/active-properties/under-contract/payment-process',
        label: 'Payment Process',
      },
      {
        id: '67b0b8899a1e4304421b441b',
        doc: 32,
        url: '/active-properties/under-contract/payment-process/payment-plan-setup',
        label: 'Payment Plan Setup',
      },
    ],
    _status: 'published',
  },
]
