import type { Availability } from '@payload-types'

type CreateAvailability = Omit<
  Availability,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const specialAvailability: CreateAvailability[] = [
  // Special States (Parent)
  {
    title: 'Special States',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'special-states',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b539b',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
    ],
    _status: 'published',
  },
  // Pre-Release (Child of Special States)
  {
    title: 'Pre-Release',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'pre-release',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b53a0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b7de9a1e4304421b53a1',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
    ],
    _status: 'published',
  },
  // Coming Soon (Child of Pre-Release)
  {
    title: 'Coming Soon',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'coming-soon',
    slugLock: true,
    parent: 202,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53a7',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b53a8',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b53a9',
        doc: 203,
        url: '/special-states/pre-release/coming-soon',
        label: 'Coming Soon',
      },
    ],
    _status: 'published',
  },
  // Under Construction (Child of Coming Soon)
  {
    title: 'Under Construction',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:50.276Z',
    slug: 'under-construction',
    slugLock: true,
    parent: 203,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53b0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b53b1',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b53b2',
        doc: 203,
        url: '/special-states/pre-release/coming-soon',
        label: 'Coming Soon',
      },
      {
        id: '67b0b8449a1e4304421b53b3',
        doc: 204,
        url: '/special-states/pre-release/coming-soon/under-construction',
        label: 'Under Construction',
      },
    ],
    _status: 'published',
  },
  // Final Touches (Child of Coming Soon)
  {
    title: 'Final Touches',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:50.276Z',
    slug: 'final-touches',
    slugLock: true,
    parent: 203,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53c0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b53c1',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b53c2',
        doc: 203,
        url: '/special-states/pre-release/coming-soon',
        label: 'Coming Soon',
      },
      {
        id: '67b0b8449a1e4304421b53c3',
        doc: 205,
        url: '/special-states/pre-release/coming-soon/final-touches',
        label: 'Final Touches',
      },
    ],
    _status: 'published',
  },
  // Launch Preparation (Child of Coming Soon)
  {
    title: 'Launch Preparation',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:50.276Z',
    slug: 'launch-preparation',
    slugLock: true,
    parent: 203,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53d0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b53d1',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b53d2',
        doc: 203,
        url: '/special-states/pre-release/coming-soon',
        label: 'Coming Soon',
      },
      {
        id: '67b0b8449a1e4304421b53d3',
        doc: 206,
        url: '/special-states/pre-release/coming-soon/launch-preparation',
        label: 'Launch Preparation',
      },
    ],
    _status: 'published',
  },
  // Off-Market (Child of Pre-Release)
  {
    title: 'Off-Market',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:50.276Z',
    slug: 'off-market',
    slugLock: true,
    parent: 202,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53e0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b53e1',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b53e2',
        doc: 207,
        url: '/special-states/pre-release/off-market',
        label: 'Off-Market',
      },
    ],
    _status: 'published',
  },
  // Private Listing (Child of Off-Market)
  {
    title: 'Private Listing',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:50.276Z',
    slug: 'private-listing',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b53f0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b53f1',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b53f2',
        doc: 207,
        url: '/special-states/pre-release/off-market',
        label: 'Off-Market',
      },
      {
        id: '67b0b8449a1e4304421b53f3',
        doc: 208,
        url: '/special-states/pre-release/off-market/private-listing',
        label: 'Private Listing',
      },
    ],
    _status: 'published',
  },
  // VIP Access Only (Child of Off-Market)
  {
    title: 'VIP Access Only',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:57:50.276Z',
    slug: 'vip-access-only',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5400',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5401',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b5402',
        doc: 207,
        url: '/special-states/pre-release/off-market',
        label: 'Off-Market',
      },
      {
        id: '67b0b8449a1e4304421b5403',
        doc: 209,
        url: '/special-states/pre-release/off-market/vip-access-only',
        label: 'VIP Access Only',
      },
    ],
    _status: 'published',
  },
  // Exclusive Release (Child of Off-Market)
  {
    title: 'Exclusive Release',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:58:50.276Z',
    slug: 'exclusive-release',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5410',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5411',
        doc: 202,
        url: '/special-states/pre-release',
        label: 'Pre-Release',
      },
      {
        id: '67b0b8449a1e4304421b5412',
        doc: 207,
        url: '/special-states/pre-release/off-market',
        label: 'Off-Market',
      },
      {
        id: '67b0b8449a1e4304421b5413',
        doc: 210,
        url: '/special-states/pre-release/off-market/exclusive-release',
        label: 'Exclusive Release',
      },
    ],
    _status: 'published',
  },
  // Archive (Child of Special States)
  {
    title: 'Archive',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:50.276Z',
    slug: 'archive',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5420',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5421',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
    ],
    _status: 'published',
  },
  // Permanently Removed (Child of Archive)
  {
    title: 'Permanently Removed',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:50.276Z',
    slug: 'permanently-removed',
    slugLock: true,
    parent: 211,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5430',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5431',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5432',
        doc: 212,
        url: '/special-states/archive/permanently-removed',
        label: 'Permanently Removed',
      },
    ],
    _status: 'published',
  },
  // No Longer Available (Child of Permanently Removed)
  {
    title: 'No Longer Available',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:01:50.276Z',
    slug: 'no-longer-available',
    slugLock: true,
    parent: 212,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5440',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5441',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5442',
        doc: 212,
        url: '/special-states/archive/permanently-removed',
        label: 'Permanently Removed',
      },
      {
        id: '67b0b8449a1e4304421b5443',
        doc: 213,
        url: '/special-states/archive/permanently-removed/no-longer-available',
        label: 'No Longer Available',
      },
    ],
    _status: 'published',
  },
  // Property Demolished (Child of Permanently Removed)
  {
    title: 'Property Demolished',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:02:50.276Z',
    slug: 'property-demolished',
    slugLock: true,
    parent: 212,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5450',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5451',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5452',
        doc: 212,
        url: '/special-states/archive/permanently-removed',
        label: 'Permanently Removed',
      },
      {
        id: '67b0b8449a1e4304421b5453',
        doc: 214,
        url: '/special-states/archive/permanently-removed/property-demolished',
        label: 'Property Demolished',
      },
    ],
    _status: 'published',
  },
  // Zoning Changed (Child of Permanently Removed)
  {
    title: 'Zoning Changed',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:03:50.276Z',
    slug: 'zoning-changed',
    slugLock: true,
    parent: 212,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5460',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5461',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5462',
        doc: 212,
        url: '/special-states/archive/permanently-removed',
        label: 'Permanently Removed',
      },
      {
        id: '67b0b8449a1e4304421b5463',
        doc: 215,
        url: '/special-states/archive/permanently-removed/zoning-changed',
        label: 'Zoning Changed',
      },
    ],
    _status: 'published',
  },
  // Historical Record (Child of Archive)
  {
    title: 'Historical Record',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:04:50.276Z',
    slug: 'historical-record',
    slugLock: true,
    parent: 211,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5470',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5471',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5472',
        doc: 216,
        url: '/special-states/archive/historical-record',
        label: 'Historical Record',
      },
    ],
    _status: 'published',
  },
  // Past Listing (Child of Historical Record)
  {
    title: 'Past Listing',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:05:50.276Z',
    slug: 'past-listing',
    slugLock: true,
    parent: 216,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5480',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5481',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5482',
        doc: 216,
        url: '/special-states/archive/historical-record',
        label: 'Historical Record',
      },
      {
        id: '67b0b8449a1e4304421b5483',
        doc: 217,
        url: '/special-states/archive/historical-record/past-listing',
        label: 'Past Listing',
      },
    ],
    _status: 'published',
  },
  // Previous Versions (Child of Historical Record)
  {
    title: 'Previous Versions',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:06:50.276Z',
    slug: 'previous-versions',
    slugLock: true,
    parent: 216,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b5490',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b5491',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b5492',
        doc: 216,
        url: '/special-states/archive/historical-record',
        label: 'Historical Record',
      },
      {
        id: '67b0b8449a1e4304421b5493',
        doc: 218,
        url: '/special-states/archive/historical-record/previous-versions',
        label: 'Previous Versions',
      },
    ],
    _status: 'published',
  },
  // Market Analysis (Child of Historical Record)
  {
    title: 'Market Analysis',
    allowInquiries: false,
    showInSearch: false,
    color: 'purple',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:07:50.276Z',
    slug: 'market-analysis',
    slugLock: true,
    parent: 216,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b54a0',
        doc: 201,
        url: '/special-states',
        label: 'Special States',
      },
      {
        id: '67b0b8449a1e4304421b54a1',
        doc: 211,
        url: '/special-states/archive',
        label: 'Archive',
      },
      {
        id: '67b0b8449a1e4304421b54a2',
        doc: 216,
        url: '/special-states/archive/historical-record',
        label: 'Historical Record',
      },
      {
        id: '67b0b8449a1e4304421b54a3',
        doc: 219,
        url: '/special-states/archive/historical-record/market-analysis',
        label: 'Market Analysis',
      },
    ],
    _status: 'published',
  },
]
