import type { Contract } from '@payload-types'

type CreateContract = Omit<
  Contract,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockRentalContracts: CreateContract[] = [
  // Rental Contracts (Parent)
  {
    title: 'Rental Contracts',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'rental-contracts',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b439c',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
    ],
    _status: 'published',
  },
  // Long-Term Rental (Child of Rental Contracts)
  {
    title: 'Long-Term Rental',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'long-term-rental',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b43a2',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b7de9a1e4304421b43a3',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
    ],
    _status: 'published',
  },
  // Annual Contract (Child of Long-Term Rental)
  {
    title: 'Annual Contract',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'annual-contract',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43aa',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43ab',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43ac',
        doc: 102,
        url: '/rental-contracts/long-term-rental/annual-contract',
        label: 'Annual Contract',
      },
    ],
    _status: 'published',
  },
  // Standard Annual Contract (Child of Annual Contract)
  {
    title: 'Standard (1 Year)',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:50.276Z',
    slug: 'standard-annual',
    slugLock: true,
    parent: 102,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43ad',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43ae',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43af',
        doc: 102,
        url: '/rental-contracts/long-term-rental/annual-contract',
        label: 'Annual Contract',
      },
      {
        id: '67b0b8449a1e4304421b43b0',
        doc: 103,
        url: '/rental-contracts/long-term-rental/annual-contract/standard-annual',
        label: 'Standard (1 Year)',
      },
    ],
    _status: 'published',
  },
  // Extended Annual Contract (Child of Annual Contract)
  {
    title: 'Extended (2+ Years)',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:50.276Z',
    slug: 'extended-annual',
    slugLock: true,
    parent: 102,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43b1',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43b2',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43b3',
        doc: 102,
        url: '/rental-contracts/long-term-rental/annual-contract',
        label: 'Annual Contract',
      },
      {
        id: '67b0b8449a1e4304421b43b4',
        doc: 104,
        url: '/rental-contracts/long-term-rental/annual-contract/extended-annual',
        label: 'Extended (2+ Years)',
      },
    ],
    _status: 'published',
  },
  // Corporate Lease (Child of Annual Contract)
  {
    title: 'Corporate Lease',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:50.276Z',
    slug: 'corporate-lease',
    slugLock: true,
    parent: 102,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43b5',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43b6',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43b7',
        doc: 102,
        url: '/rental-contracts/long-term-rental/annual-contract',
        label: 'Annual Contract',
      },
      {
        id: '67b0b8449a1e4304421b43b8',
        doc: 105,
        url: '/rental-contracts/long-term-rental/annual-contract/corporate-lease',
        label: 'Corporate Lease',
      },
    ],
    _status: 'published',
  },
  // Semi-Annual Contract (Child of Long-Term Rental)
  {
    title: 'Semi-Annual Contract',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:50.276Z',
    slug: 'semi-annual-contract',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43b9',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43ba',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43bb',
        doc: 106,
        url: '/rental-contracts/long-term-rental/semi-annual-contract',
        label: 'Semi-Annual Contract',
      },
    ],
    _status: 'published',
  },
  // 6-Month Term (Child of Semi-Annual Contract)
  {
    title: '6-Month Term',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:50.276Z',
    slug: '6-month-term',
    slugLock: true,
    parent: 106,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43bc',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43bd',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43be',
        doc: 106,
        url: '/rental-contracts/long-term-rental/semi-annual-contract',
        label: 'Semi-Annual Contract',
      },
      {
        id: '67b0b8449a1e4304421b43bf',
        doc: 107,
        url: '/rental-contracts/long-term-rental/semi-annual-contract/6-month-term',
        label: '6-Month Term',
      },
    ],
    _status: 'published',
  },
  // Renewable Option (Child of Semi-Annual Contract)
  {
    title: 'Renewable Option',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:57:50.276Z',
    slug: 'renewable-option',
    slugLock: true,
    parent: 106,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43c0',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43c1',
        doc: 101,
        url: '/rental-contracts/long-term-rental',
        label: 'Long-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43c2',
        doc: 106,
        url: '/rental-contracts/long-term-rental/semi-annual-contract',
        label: 'Semi-Annual Contract',
      },
      {
        id: '67b0b8449a1e4304421b43c3',
        doc: 108,
        url: '/rental-contracts/long-term-rental/semi-annual-contract/renewable-option',
        label: 'Renewable Option',
      },
    ],
    _status: 'published',
  },
  // Short-Term Rental (Child of Rental Contracts)
  {
    title: 'Short-Term Rental',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:58:50.276Z',
    slug: 'short-term-rental',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43c4',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43c5',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
    ],
    _status: 'published',
  },
  // Holiday Home (Child of Short-Term Rental)
  {
    title: 'Holiday Home',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:50.276Z',
    slug: 'holiday-home',
    slugLock: true,
    parent: 109,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43c6',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43c7',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43c8',
        doc: 110,
        url: '/rental-contracts/short-term-rental/holiday-home',
        label: 'Holiday Home',
      },
    ],
    _status: 'published',
  },
  // Daily Rate (Child of Holiday Home)
  {
    title: 'Daily Rate',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:50.276Z',
    slug: 'daily-rate',
    slugLock: true,
    parent: 110,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43c9',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43ca',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43cb',
        doc: 110,
        url: '/rental-contracts/short-term-rental/holiday-home',
        label: 'Holiday Home',
      },
      {
        id: '67b0b8449a1e4304421b43cc',
        doc: 111,
        url: '/rental-contracts/short-term-rental/holiday-home/daily-rate',
        label: 'Daily Rate',
      },
    ],
    _status: 'published',
  },
  // Weekly Rate (Child of Holiday Home)
  {
    title: 'Weekly Rate',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:01:50.276Z',
    slug: 'weekly-rate',
    slugLock: true,
    parent: 110,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43cd',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43ce',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43cf',
        doc: 110,
        url: '/rental-contracts/short-term-rental/holiday-home',
        label: 'Holiday Home',
      },
      {
        id: '67b0b8449a1e4304421b43d0',
        doc: 112,
        url: '/rental-contracts/short-term-rental/holiday-home/weekly-rate',
        label: 'Weekly Rate',
      },
    ],
    _status: 'published',
  },
  // Monthly Rate (Child of Holiday Home)
  {
    title: 'Monthly Rate',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:02:50.276Z',
    slug: 'monthly-rate',
    slugLock: true,
    parent: 110,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43d1',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43d2',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43d3',
        doc: 110,
        url: '/rental-contracts/short-term-rental/holiday-home',
        label: 'Holiday Home',
      },
      {
        id: '67b0b8449a1e4304421b43d4',
        doc: 113,
        url: '/rental-contracts/short-term-rental/holiday-home/monthly-rate',
        label: 'Monthly Rate',
      },
    ],
    _status: 'published',
  },
  // Seasonal Rental (Child of Short-Term Rental)
  {
    title: 'Seasonal Rental',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:03:50.276Z',
    slug: 'seasonal-rental',
    slugLock: true,
    parent: 109,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43d5',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43d6',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43d7',
        doc: 114,
        url: '/rental-contracts/short-term-rental/seasonal-rental',
        label: 'Seasonal Rental',
      },
    ],
    _status: 'published',
  },
  // Summer Season (Child of Seasonal Rental)
  {
    title: 'Summer Season',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:04:50.276Z',
    slug: 'summer-season',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43d8',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43d9',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43da',
        doc: 114,
        url: '/rental-contracts/short-term-rental/seasonal-rental',
        label: 'Seasonal Rental',
      },
      {
        id: '67b0b8449a1e4304421b43db',
        doc: 115,
        url: '/rental-contracts/short-term-rental/seasonal-rental/summer-season',
        label: 'Summer Season',
      },
    ],
    _status: 'published',
  },
  // Winter Season (Child of Seasonal Rental)
  {
    title: 'Winter Season',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:05:50.276Z',
    slug: 'winter-season',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43dc',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43dd',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43de',
        doc: 114,
        url: '/rental-contracts/short-term-rental/seasonal-rental',
        label: 'Seasonal Rental',
      },
      {
        id: '67b0b8449a1e4304421b43df',
        doc: 116,
        url: '/rental-contracts/short-term-rental/seasonal-rental/winter-season',
        label: 'Winter Season',
      },
    ],
    _status: 'published',
  },
  // Peak Season (Child of Seasonal Rental)
  {
    title: 'Peak Season',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:06:50.276Z',
    slug: 'peak-season',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43e0',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43e1',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43e2',
        doc: 114,
        url: '/rental-contracts/short-term-rental/seasonal-rental',
        label: 'Seasonal Rental',
      },
      {
        id: '67b0b8449a1e4304421b43e3',
        doc: 117,
        url: '/rental-contracts/short-term-rental/seasonal-rental/peak-season',
        label: 'Peak Season',
      },
    ],
    _status: 'published',
  },
  // Corporate Short Stay (Child of Short-Term Rental)
  {
    title: 'Corporate Short Stay',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:07:50.276Z',
    slug: 'corporate-short-stay',
    slugLock: true,
    parent: 109,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43e4',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43e5',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43e6',
        doc: 118,
        url: '/rental-contracts/short-term-rental/corporate-short-stay',
        label: 'Corporate Short Stay',
      },
    ],
    _status: 'published',
  },
  // Business Travel (Child of Corporate Short Stay)
  {
    title: 'Business Travel',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:08:50.276Z',
    slug: 'business-travel',
    slugLock: true,
    parent: 118,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43e7',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43e8',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43e9',
        doc: 118,
        url: '/rental-contracts/short-term-rental/corporate-short-stay',
        label: 'Corporate Short Stay',
      },
      {
        id: '67b0b8449a1e4304421b43ea',
        doc: 119,
        url: '/rental-contracts/short-term-rental/corporate-short-stay/business-travel',
        label: 'Business Travel',
      },
    ],
    _status: 'published',
  },
  // Project-Based (Child of Corporate Short Stay)
  {
    title: 'Project-Based',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:09:50.276Z',
    slug: 'project-based',
    slugLock: true,
    parent: 118,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43eb',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43ec',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43ed',
        doc: 118,
        url: '/rental-contracts/short-term-rental/corporate-short-stay',
        label: 'Corporate Short Stay',
      },
      {
        id: '67b0b8449a1e4304421b43ee',
        doc: 120,
        url: '/rental-contracts/short-term-rental/corporate-short-stay/project-based',
        label: 'Project-Based',
      },
    ],
    _status: 'published',
  },
  // Relocation Period (Child of Corporate Short Stay)
  {
    title: 'Relocation Period',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:10:50.276Z',
    slug: 'relocation-period',
    slugLock: true,
    parent: 118,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43ef',
        doc: 100,
        url: '/rental-contracts',
        label: 'Rental Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43f0',
        doc: 109,
        url: '/rental-contracts/short-term-rental',
        label: 'Short-Term Rental',
      },
      {
        id: '67b0b8449a1e4304421b43f1',
        doc: 118,
        url: '/rental-contracts/short-term-rental/corporate-short-stay',
        label: 'Corporate Short Stay',
      },
      {
        id: '67b0b8449a1e4304421b43f2',
        doc: 121,
        url: '/rental-contracts/short-term-rental/corporate-short-stay/relocation-period',
        label: 'Relocation Period',
      },
    ],
    _status: 'published',
  },
]
