import type { Contract } from '@payload-types'

type CreateContract = Omit<
  Contract,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockSpecialArrangements: CreateContract[] = [
  // Root Category - Special Arrangements
  {
    title: 'Special Arrangements',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:00:00.000Z',
    slug: 'special-arrangements',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
    ],
    _status: 'published',
  },

  // Main Category - Flexible Terms
  {
    title: 'Flexible Terms',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:01:00.000Z',
    slug: 'flexible-terms',
    slugLock: true,
    parent: 300,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
    ],
    _status: 'published',
  },

  // Sub-Category - Multiple Cheques
  {
    title: 'Multiple Cheques',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:02:00.000Z',
    slug: 'multiple-cheques',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f3',
        doc: 302,
        url: '/special-arrangements/flexible-terms/multiple-cheques',
        label: 'Multiple Cheques',
      },
    ],
    _status: 'published',
  },

  // Items under Multiple Cheques
  {
    title: '1 Cheque',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:03:00.000Z',
    slug: '1-cheque',
    slugLock: true,
    parent: 302,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f3',
        doc: 302,
        url: '/special-arrangements/flexible-terms/multiple-cheques',
        label: 'Multiple Cheques',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f4',
        doc: 303,
        url: '/special-arrangements/flexible-terms/multiple-cheques/1-cheque',
        label: '1 Cheque',
      },
    ],
    _status: 'published',
  },
  {
    title: '2-4 Cheques',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:04:00.000Z',
    slug: '2-4-cheques',
    slugLock: true,
    parent: 302,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f3',
        doc: 302,
        url: '/special-arrangements/flexible-terms/multiple-cheques',
        label: 'Multiple Cheques',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f5',
        doc: 304,
        url: '/special-arrangements/flexible-terms/multiple-cheques/2-4-cheques',
        label: '2-4 Cheques',
      },
    ],
    _status: 'published',
  },
  {
    title: '6-12 Cheques',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:05:00.000Z',
    slug: '6-12-cheques',
    slugLock: true,
    parent: 302,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f3',
        doc: 302,
        url: '/special-arrangements/flexible-terms/multiple-cheques',
        label: 'Multiple Cheques',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f6',
        doc: 305,
        url: '/special-arrangements/flexible-terms/multiple-cheques/6-12-cheques',
        label: '6-12 Cheques',
      },
    ],
    _status: 'published',
  },

  // Sub-Category - Security Deposit
  {
    title: 'Security Deposit',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:06:00.000Z',
    slug: 'security-deposit',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f7',
        doc: 306,
        url: '/special-arrangements/flexible-terms/security-deposit',
        label: 'Security Deposit',
      },
    ],
    _status: 'published',
  },

  // Items under Security Deposit
  {
    title: 'Standard',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:07:00.000Z',
    slug: 'standard',
    slugLock: true,
    parent: 306,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f7',
        doc: 306,
        url: '/special-arrangements/flexible-terms/security-deposit',
        label: 'Security Deposit',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f8',
        doc: 307,
        url: '/special-arrangements/flexible-terms/security-deposit/standard',
        label: 'Standard',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Enhanced',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:08:00.000Z',
    slug: 'enhanced',
    slugLock: true,
    parent: 306,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f7',
        doc: 306,
        url: '/special-arrangements/flexible-terms/security-deposit',
        label: 'Security Deposit',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f9',
        doc: 308,
        url: '/special-arrangements/flexible-terms/security-deposit/enhanced',
        label: 'Enhanced',
      },
    ],
    _status: 'published',
  },

  // Sub-Category - Maintenance Terms
  {
    title: 'Maintenance Terms',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:09:00.000Z',
    slug: 'maintenance-terms',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f110',
        doc: 309,
        url: '/special-arrangements/flexible-terms/maintenance-terms',
        label: 'Maintenance Terms',
      },
    ],
    _status: 'published',
  },

  // Items under Maintenance Terms
  {
    title: 'Owner Maintained',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:10:00.000Z',
    slug: 'owner-maintained',
    slugLock: true,
    parent: 309,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f110',
        doc: 309,
        url: '/special-arrangements/flexible-terms/maintenance-terms',
        label: 'Maintenance Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f111',
        doc: 310,
        url: '/special-arrangements/flexible-terms/maintenance-terms/owner-maintained',
        label: 'Owner Maintained',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Tenant Maintained',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:11:00.000Z',
    slug: 'tenant-maintained',
    slugLock: true,
    parent: 309,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f110',
        doc: 309,
        url: '/special-arrangements/flexible-terms/maintenance-terms',
        label: 'Maintenance Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f112',
        doc: 311,
        url: '/special-arrangements/flexible-terms/maintenance-terms/tenant-maintained',
        label: 'Tenant Maintained',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Mixed Responsibility',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:12:00.000Z',
    slug: 'mixed-responsibility',
    slugLock: true,
    parent: 309,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f2',
        doc: 301,
        url: '/special-arrangements/flexible-terms',
        label: 'Flexible Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f110',
        doc: 309,
        url: '/special-arrangements/flexible-terms/maintenance-terms',
        label: 'Maintenance Terms',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f113',
        doc: 312,
        url: '/special-arrangements/flexible-terms/maintenance-terms/mixed-responsibility',
        label: 'Mixed Responsibility',
      },
    ],
    _status: 'published',
  },

  // Main Category - Commercial Conversion
  {
    title: 'Commercial Conversion',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:13:00.000Z',
    slug: 'commercial-conversion',
    slugLock: true,
    parent: 300,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
    ],
    _status: 'published',
  },

  // Sub-Category - Mixed-Use License
  {
    title: 'Mixed-Use License',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:14:00.000Z',
    slug: 'mixed-use-license',
    slugLock: true,
    parent: 313,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f115',
        doc: 314,
        url: '/special-arrangements/commercial-conversion/mixed-use-license',
        label: 'Mixed-Use License',
      },
    ],
    _status: 'published',
  },

  // Items under Mixed-Use License
  {
    title: 'Home Office',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:15:00.000Z',
    slug: 'home-office',
    slugLock: true,
    parent: 314,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f115',
        doc: 314,
        url: '/special-arrangements/commercial-conversion/mixed-use-license',
        label: 'Mixed-Use License',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f116',
        doc: 315,
        url: '/special-arrangements/commercial-conversion/mixed-use-license/home-office',
        label: 'Home Office',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Creative Space',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:16:00.000Z',
    slug: 'creative-space',
    slugLock: true,
    parent: 314,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f115',
        doc: 314,
        url: '/special-arrangements/commercial-conversion/mixed-use-license',
        label: 'Mixed-Use License',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f117',
        doc: 316,
        url: '/special-arrangements/commercial-conversion/mixed-use-license/creative-space',
        label: 'Creative Space',
      },
    ],
    _status: 'published',
  },

  // Sub-Category - Commercial License
  {
    title: 'Commercial License',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:17:00.000Z',
    slug: 'commercial-license',
    slugLock: true,
    parent: 313,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f118',
        doc: 317,
        url: '/special-arrangements/commercial-conversion/commercial-license',
        label: 'Commercial License',
      },
    ],
    _status: 'published',
  },

  // Items under Commercial License
  {
    title: 'Professional Office',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:18:00.000Z',
    slug: 'professional-office',
    slugLock: true,
    parent: 317,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f118',
        doc: 317,
        url: '/special-arrangements/commercial-conversion/commercial-license',
        label: 'Commercial License',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f119',
        doc: 318,
        url: '/special-arrangements/commercial-conversion/commercial-license/professional-office',
        label: 'Professional Office',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Service Business',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:19:00.000Z',
    slug: 'service-business',
    slugLock: true,
    parent: 317,
    breadcrumbs: [
      {
        id: '65f1f1f1f1f1f1f1f1f1f1f1',
        doc: 300,
        url: '/special-arrangements',
        label: 'Special Arrangements',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f114',
        doc: 313,
        url: '/special-arrangements/commercial-conversion',
        label: 'Commercial Conversion',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f118',
        doc: 317,
        url: '/special-arrangements/commercial-conversion/commercial-license',
        label: 'Commercial License',
      },
      {
        id: '65f1f1f1f1f1f1f1f1f1f120',
        doc: 319,
        url: '/special-arrangements/commercial-conversion/commercial-license/service-business',
        label: 'Service Business',
      },
    ],
    _status: 'published',
  },
]
