import type { Classification } from '@payload-types'

type CreateClassification = Omit<
  Classification,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockMarketSegments: CreateClassification[] = [
  // Market Segment (Parent)
  {
    title: 'Market Segment',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:00:00.000Z',
    slug: 'market-segment',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
    ],
    _status: 'published',
  },
  // Target Residents (First Level)
  {
    title: 'Target Residents',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:01:00.000Z',
    slug: 'target-residents',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
    ],
    _status: 'published',
  },
  // Families (Second Level)
  {
    title: 'Families',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:02:00.000Z',
    slug: 'families',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f3',
        doc: 402,
        url: '/market-segment/target-residents/families',
        label: 'Families',
      },
    ],
    _status: 'published',
  },
  // Small Family
  {
    title: 'Small Family',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'text',
            version: 1,
            text: '2-3 members',
          },
        ],
        direction: null,
        format: '',
        indent: 0,
        version: 1,
      },
    },
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:03:00.000Z',
    slug: 'small-family',
    slugLock: true,
    parent: 402,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f3',
        doc: 402,
        url: '/market-segment/target-residents/families',
        label: 'Families',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f4',
        doc: 403,
        url: '/market-segment/target-residents/families/small-family',
        label: 'Small Family',
      },
    ],
    _status: 'published',
  },
  // Large Family
  {
    title: 'Large Family',
    description: {
      root: {
        type: 'root',
        children: [
          {
            type: 'text',
            version: 1,
            text: '4+ members',
          },
        ],
        direction: null,
        format: '',
        indent: 0,
        version: 1,
      },
    },
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:04:00.000Z',
    slug: 'large-family',
    slugLock: true,
    parent: 402,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f3',
        doc: 402,
        url: '/market-segment/target-residents/families',
        label: 'Families',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f5',
        doc: 404,
        url: '/market-segment/target-residents/families/large-family',
        label: 'Large Family',
      },
    ],
    _status: 'published',
  },
  // Professionals (Second Level)
  {
    title: 'Professionals',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:05:00.000Z',
    slug: 'professionals',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f6',
        doc: 405,
        url: '/market-segment/target-residents/professionals',
        label: 'Professionals',
      },
    ],
    _status: 'published',
  },
  // Young Professionals
  {
    title: 'Young Professionals',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:06:00.000Z',
    slug: 'young-professionals',
    slugLock: true,
    parent: 405,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f6',
        doc: 405,
        url: '/market-segment/target-residents/professionals',
        label: 'Professionals',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f7',
        doc: 406,
        url: '/market-segment/target-residents/professionals/young-professionals',
        label: 'Young Professionals',
      },
    ],
    _status: 'published',
  },
  // Executives
  {
    title: 'Executives',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:07:00.000Z',
    slug: 'executives',
    slugLock: true,
    parent: 405,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f6',
        doc: 405,
        url: '/market-segment/target-residents/professionals',
        label: 'Professionals',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f8',
        doc: 407,
        url: '/market-segment/target-residents/professionals/executives',
        label: 'Executives',
      },
    ],
    _status: 'published',
  },
  // Singles (Second Level)
  {
    title: 'Singles',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:08:00.000Z',
    slug: 'singles',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f9',
        doc: 408,
        url: '/market-segment/target-residents/singles',
        label: 'Singles',
      },
    ],
    _status: 'published',
  },
  // Students
  {
    title: 'Students',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:09:00.000Z',
    slug: 'students',
    slugLock: true,
    parent: 408,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f9',
        doc: 408,
        url: '/market-segment/target-residents/singles',
        label: 'Singles',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fa',
        doc: 409,
        url: '/market-segment/target-residents/singles/students',
        label: 'Students',
      },
    ],
    _status: 'published',
  },
  // Working Singles
  {
    title: 'Working Singles',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:10:00.000Z',
    slug: 'working-singles',
    slugLock: true,
    parent: 408,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f9',
        doc: 408,
        url: '/market-segment/target-residents/singles',
        label: 'Singles',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fb',
        doc: 410,
        url: '/market-segment/target-residents/singles/working-singles',
        label: 'Working Singles',
      },
    ],
    _status: 'published',
  },
  // Couples (Second Level)
  {
    title: 'Couples',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:11:00.000Z',
    slug: 'couples',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fc',
        doc: 411,
        url: '/market-segment/target-residents/couples',
        label: 'Couples',
      },
    ],
    _status: 'published',
  },
  // Young Couples
  {
    title: 'Young Couples',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:12:00.000Z',
    slug: 'young-couples',
    slugLock: true,
    parent: 411,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fc',
        doc: 411,
        url: '/market-segment/target-residents/couples',
        label: 'Couples',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fd',
        doc: 412,
        url: '/market-segment/target-residents/couples/young-couples',
        label: 'Young Couples',
      },
    ],
    _status: 'published',
  },
  // Retired Couples
  {
    title: 'Retired Couples',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:13:00.000Z',
    slug: 'retired-couples',
    slugLock: true,
    parent: 411,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f2',
        doc: 401,
        url: '/market-segment/target-residents',
        label: 'Target Residents',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fc',
        doc: 411,
        url: '/market-segment/target-residents/couples',
        label: 'Couples',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e6fe',
        doc: 413,
        url: '/market-segment/target-residents/couples/retired-couples',
        label: 'Retired Couples',
      },
    ],
    _status: 'published',
  },
  // Lifestyle Focus (First Level)
  {
    title: 'Lifestyle Focus',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:14:00.000Z',
    slug: 'lifestyle-focus',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
    ],
    _status: 'published',
  },
  // Urban Living (Second Level)
  {
    title: 'Urban Living',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:15:00.000Z',
    slug: 'urban-living',
    slugLock: true,
    parent: 414,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f2',
        doc: 415,
        url: '/market-segment/lifestyle-focus/urban-living',
        label: 'Urban Living',
      },
    ],
    _status: 'published',
  },
  // City Center
  {
    title: 'City Center',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:16:00.000Z',
    slug: 'city-center',
    slugLock: true,
    parent: 415,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f2',
        doc: 415,
        url: '/market-segment/lifestyle-focus/urban-living',
        label: 'Urban Living',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f3',
        doc: 416,
        url: '/market-segment/lifestyle-focus/urban-living/city-center',
        label: 'City Center',
      },
    ],
    _status: 'published',
  },
  // Business District
  {
    title: 'Business District',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:17:00.000Z',
    slug: 'business-district',
    slugLock: true,
    parent: 415,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f2',
        doc: 415,
        url: '/market-segment/lifestyle-focus/urban-living',
        label: 'Urban Living',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f4',
        doc: 417,
        url: '/market-segment/lifestyle-focus/urban-living/business-district',
        label: 'Business District',
      },
    ],
    _status: 'published',
  },
  // Community Living (Second Level)
  {
    title: 'Community Living',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:18:00.000Z',
    slug: 'community-living',
    slugLock: true,
    parent: 414,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f5',
        doc: 418,
        url: '/market-segment/lifestyle-focus/community-living',
        label: 'Community Living',
      },
    ],
    _status: 'published',
  },
  // Family-Oriented
  {
    title: 'Family-Oriented',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:19:00.000Z',
    slug: 'family-oriented',
    slugLock: true,
    parent: 418,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f5',
        doc: 418,
        url: '/market-segment/lifestyle-focus/community-living',
        label: 'Community Living',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f6',
        doc: 419,
        url: '/market-segment/lifestyle-focus/community-living/family-oriented',
        label: 'Family-Oriented',
      },
    ],
    _status: 'published',
  },
  // Active Lifestyle
  {
    title: 'Active Lifestyle',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:20:00.000Z',
    slug: 'active-lifestyle',
    slugLock: true,
    parent: 418,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f5',
        doc: 418,
        url: '/market-segment/lifestyle-focus/community-living',
        label: 'Community Living',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f7',
        doc: 420,
        url: '/market-segment/lifestyle-focus/community-living/active-lifestyle',
        label: 'Active Lifestyle',
      },
    ],
    _status: 'published',
  },
  // Quiet Living (Second Level)
  {
    title: 'Quiet Living',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:21:00.000Z',
    slug: 'quiet-living',
    slugLock: true,
    parent: 414,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f8',
        doc: 421,
        url: '/market-segment/lifestyle-focus/quiet-living',
        label: 'Quiet Living',
      },
    ],
    _status: 'published',
  },
  // Suburban
  {
    title: 'Suburban',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:22:00.000Z',
    slug: 'suburban',
    slugLock: true,
    parent: 421,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f8',
        doc: 421,
        url: '/market-segment/lifestyle-focus/quiet-living',
        label: 'Quiet Living',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f9',
        doc: 422,
        url: '/market-segment/lifestyle-focus/quiet-living/suburban',
        label: 'Suburban',
      },
    ],
    _status: 'published',
  },
  // Residential Focus
  {
    title: 'Residential Focus',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:23:00.000Z',
    slug: 'residential-focus',
    slugLock: true,
    parent: 421,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e6f1',
        doc: 400,
        url: '/market-segment',
        label: 'Market Segment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f1',
        doc: 414,
        url: '/market-segment/lifestyle-focus',
        label: 'Lifestyle Focus',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7f8',
        doc: 421,
        url: '/market-segment/lifestyle-focus/quiet-living',
        label: 'Quiet Living',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e7fa',
        doc: 423,
        url: '/market-segment/lifestyle-focus/quiet-living/residential-focus',
        label: 'Residential Focus',
      },
    ],
    _status: 'published',
  },
]
