import type { Classification } from '@payload-types'

type CreateClassification = Omit<
  Classification,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockPropertyTypes: CreateClassification[] = [
  // Root Category
  {
    title: 'Property Types',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:00:00.000Z',
    slug: 'property-types',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
    ],
    _status: 'published',
  },
  // Residential Units Category
  {
    title: 'Residential Units',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:01:00.000Z',
    slug: 'residential-units',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
    ],
    _status: 'published',
  },
  // Apartment Category
  {
    title: 'Apartment',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:02:00.000Z',
    slug: 'apartment',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 102,
        url: '/property-types/residential-units/apartment',
        label: 'Apartment',
      },
    ],
    _status: 'published',
  },
  // Apartment Types
  {
    title: 'Studio',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:03:00.000Z',
    slug: 'studio',
    slugLock: true,
    parent: 102,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 102,
        url: '/property-types/residential-units/apartment',
        label: 'Apartment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f8',
        doc: 103,
        url: '/property-types/residential-units/apartment/studio',
        label: 'Studio',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Flat',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:04:00.000Z',
    slug: 'flat',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 102,
        url: '/property-types/residential-units/apartment',
        label: 'Apartment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f9',
        doc: 103,
        url: '/property-types/residential-units/apartment/flat',
        label: 'Flat',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Duplex',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:05:00.000Z',
    slug: 'duplex',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 102,
        url: '/property-types/residential-units/apartment',
        label: 'Apartment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fa',
        doc: 104,
        url: '/property-types/residential-units/apartment/duplex',
        label: 'Duplex',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Penthouse',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:06:00.000Z',
    slug: 'penthouse',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 102,
        url: '/property-types/residential-units/apartment',
        label: 'Apartment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fb',
        doc: 105,
        url: '/property-types/residential-units/apartment/penthouse',
        label: 'Penthouse',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Loft',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:07:00.000Z',
    slug: 'loft',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 102,
        url: '/property-types/residential-units/apartment',
        label: 'Apartment',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fc',
        doc: 106,
        url: '/property-types/residential-units/apartment/loft',
        label: 'Loft',
      },
    ],
    _status: 'published',
  },
  // Villa Category
  {
    title: 'Villa',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:08:00.000Z',
    slug: 'villa',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fd',
        doc: 107,
        url: '/property-types/residential-units/villa',
        label: 'Villa',
      },
    ],
    _status: 'published',
  },
  // Villa Types
  {
    title: 'Single Family',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:09:00.000Z',
    slug: 'single-family',
    slugLock: true,
    parent: 107,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fd',
        doc: 107,
        url: '/property-types/residential-units/villa',
        label: 'Villa',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fe',
        doc: 108,
        url: '/property-types/residential-units/villa/single-family',
        label: 'Single Family',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Twin Villa',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:10:00.000Z',
    slug: 'twin-villa',
    slugLock: true,
    parent: 107,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fd',
        doc: 107,
        url: '/property-types/residential-units/villa',
        label: 'Villa',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5ff',
        doc: 109,
        url: '/property-types/residential-units/villa/twin-villa',
        label: 'Twin Villa',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Compound Villa',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:11:00.000Z',
    slug: 'compound-villa',
    slugLock: true,
    parent: 107,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 101,
        url: '/property-types/residential-units',
        label: 'Residential Units',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fd',
        doc: 107,
        url: '/property-types/residential-units/villa',
        label: 'Villa',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e600',
        doc: 110,
        url: '/property-types/residential-units/villa/compound-villa',
        label: 'Compound Villa',
      },
    ],
    _status: 'published',
  },
  // Townhouse Category
  {
    title: 'Townhouse',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:12:00.000Z',
    slug: 'townhouse',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e601',
        doc: 111,
        url: '/property-types/residential-units/townhouse',
        label: 'Townhouse',
      },
    ],
    _status: 'published',
  },
  // Townhouse Types
  {
    title: 'Standard',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:13:00.000Z',
    slug: 'standard',
    slugLock: true,
    parent: 111,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e601',
        doc: 111,
        url: '/property-types/residential-units/townhouse',
        label: 'Townhouse',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e602',
        doc: 112,
        url: '/property-types/residential-units/townhouse/standard',
        label: 'Standard',
      },
    ],
    _status: 'published',
  },
  {
    title: 'End Unit',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:14:00.000Z',
    slug: 'end-unit',
    slugLock: true,
    parent: 111,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e601',
        doc: 111,
        url: '/property-types/residential-units/townhouse',
        label: 'Townhouse',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e603',
        doc: 113,
        url: '/property-types/residential-units/townhouse/end-unit',
        label: 'End Unit',
      },
    ],
    _status: 'published',
  },
  {
    title: 'Corner Unit',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:15:00.000Z',
    slug: 'corner-unit',
    slugLock: true,
    parent: 111,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f5',
        doc: 100,
        url: '/property-types',
        label: 'Property Types',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e601',
        doc: 111,
        url: '/property-types/residential-units/townhouse',
        label: 'Townhouse',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e604',
        doc: 114,
        url: '/property-types/residential-units/townhouse/corner-unit',
        label: 'Corner Unit',
      },
    ],
    _status: 'published',
  },
]
