import type { Amenity } from '@payload-types'

type CreateAmenity = Omit<
  Amenity,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const communityAmenities: CreateAmenity[] = [
  // Community Amenities (Parent)
  {
    title: 'Community Amenities',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'community-amenities',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b439b',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
    ],
    _status: 'published',
  },
  // Lifestyle (Child of Community Amenities)
  {
    title: 'Lifestyle',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'lifestyle',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b43a0',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b7de9a1e4304421b43a1',
        doc: 401,
        url: '/community-amenities/lifestyle',
        label: 'Lifestyle',
      },
    ],
    _status: 'published',
  },
  // Community Retail (Child of Lifestyle)
  {
    title: 'Community Retail',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'community-retail',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43a7',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43a8',
        doc: 401,
        url: '/community-amenities/lifestyle',
        label: 'Lifestyle',
      },
      {
        id: '67b0b8449a1e4304421b43a9',
        doc: 402,
        url: '/community-amenities/lifestyle/community-retail',
        label: 'Community Retail',
      },
    ],
    _status: 'published',
  },
  // Restaurants & Cafes (Child of Lifestyle)
  {
    title: 'Restaurants & Cafes',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'restaurants-and-cafes',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43b0',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43b1',
        doc: 401,
        url: '/community-amenities/lifestyle',
        label: 'Lifestyle',
      },
      {
        id: '67b0b8449a1e4304421b43b2',
        doc: 403,
        url: '/community-amenities/lifestyle/restaurants-and-cafes',
        label: 'Restaurants & Cafes',
      },
    ],
    _status: 'published',
  },
  // Supermarket (Child of Lifestyle)
  {
    title: 'Supermarket',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'supermarket',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43c0',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43c1',
        doc: 401,
        url: '/community-amenities/lifestyle',
        label: 'Lifestyle',
      },
      {
        id: '67b0b8449a1e4304421b43c2',
        doc: 404,
        url: '/community-amenities/lifestyle/supermarket',
        label: 'Supermarket',
      },
    ],
    _status: 'published',
  },
  // Pharmacy (Child of Lifestyle)
  {
    title: 'Pharmacy',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'pharmacy',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43d0',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43d1',
        doc: 401,
        url: '/community-amenities/lifestyle',
        label: 'Lifestyle',
      },
      {
        id: '67b0b8449a1e4304421b43d2',
        doc: 405,
        url: '/community-amenities/lifestyle/pharmacy',
        label: 'Pharmacy',
      },
    ],
    _status: 'published',
  },
  // Beauty Salon (Child of Lifestyle)
  {
    title: 'Beauty Salon',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'beauty-salon',
    slugLock: true,
    parent: 401,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43e0',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43e1',
        doc: 401,
        url: '/community-amenities/lifestyle',
        label: 'Lifestyle',
      },
      {
        id: '67b0b8449a1e4304421b43e2',
        doc: 406,
        url: '/community-amenities/lifestyle/beauty-salon',
        label: 'Beauty Salon',
      },
    ],
    _status: 'published',
  },
  // Recreation (Child of Community Amenities)
  {
    title: 'Recreation',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'recreation',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b43f0',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b7de9a1e4304421b43f1',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
    ],
    _status: 'published',
  },
  // Walking/Jogging Tracks (Child of Recreation)
  {
    title: 'Walking/Jogging Tracks',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'walking-jogging-tracks',
    slugLock: true,
    parent: 407,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f2',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43f3',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b43f4',
        doc: 408,
        url: '/community-amenities/recreation/walking-jogging-tracks',
        label: 'Walking/Jogging Tracks',
      },
    ],
    _status: 'published',
  },
  // Community Parks (Child of Recreation)
  {
    title: 'Community Parks',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'community-parks',
    slugLock: true,
    parent: 407,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f5',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43f6',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b43f7',
        doc: 409,
        url: '/community-amenities/recreation/community-parks',
        label: 'Community Parks',
      },
    ],
    _status: 'published',
  },
  // Sports Courts (Child of Recreation)
  {
    title: 'Sports Courts',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'sports-courts',
    slugLock: true,
    parent: 407,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f8',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43f9',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b43fa',
        doc: 410,
        url: '/community-amenities/recreation/sports-courts',
        label: 'Sports Courts',
      },
    ],
    _status: 'published',
  },
  // Tennis Courts (Child of Sports Courts)
  {
    title: 'Tennis Courts',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'tennis-courts',
    slugLock: true,
    parent: 410,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43fb',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43fc',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b43fd',
        doc: 410,
        url: '/community-amenities/recreation/sports-courts',
        label: 'Sports Courts',
      },
      {
        id: '67b0b8449a1e4304421b43fe',
        doc: 411,
        url: '/community-amenities/recreation/sports-courts/tennis-courts',
        label: 'Tennis Courts',
      },
    ],
    _status: 'published',
  },
  // Basketball Courts (Child of Sports Courts)
  {
    title: 'Basketball Courts',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'basketball-courts',
    slugLock: true,
    parent: 410,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43ff',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4400',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b4401',
        doc: 410,
        url: '/community-amenities/recreation/sports-courts',
        label: 'Sports Courts',
      },
      {
        id: '67b0b8449a1e4304421b4402',
        doc: 412,
        url: '/community-amenities/recreation/sports-courts/basketball-courts',
        label: 'Basketball Courts',
      },
    ],
    _status: 'published',
  },
  // Padel Tennis Courts (Child of Sports Courts)
  {
    title: 'Padel Tennis Courts',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'padel-tennis-courts',
    slugLock: true,
    parent: 410,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4403',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4404',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b4405',
        doc: 410,
        url: '/community-amenities/recreation/sports-courts',
        label: 'Sports Courts',
      },
      {
        id: '67b0b8449a1e4304421b4406',
        doc: 413,
        url: '/community-amenities/recreation/sports-courts/padel-tennis-courts',
        label: 'Padel Tennis Courts',
      },
    ],
    _status: 'published',
  },
  // Pet-friendly Areas (Child of Recreation)
  {
    title: 'Pet-friendly Areas',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'pet-friendly-areas',
    slugLock: true,
    parent: 407,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4407',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4408',
        doc: 407,
        url: '/community-amenities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0b8449a1e4304421b4409',
        doc: 414,
        url: '/community-amenities/recreation/pet-friendly-areas',
        label: 'Pet-friendly Areas',
      },
    ],
    _status: 'published',
  },
  // Transportation (Child of Community Amenities)
  {
    title: 'Transportation',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'transportation',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b4410',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b7de9a1e4304421b4411',
        doc: 415,
        url: '/community-amenities/transportation',
        label: 'Transportation',
      },
    ],
    _status: 'published',
  },
  // Metro Station Proximity (Child of Transportation)
  {
    title: 'Metro Station Proximity',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'metro-station-proximity',
    slugLock: true,
    parent: 415,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4412',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4413',
        doc: 415,
        url: '/community-amenities/transportation',
        label: 'Transportation',
      },
      {
        id: '67b0b8449a1e4304421b4414',
        doc: 416,
        url: '/community-amenities/transportation/metro-station-proximity',
        label: 'Metro Station Proximity',
      },
    ],
    _status: 'published',
  },
  // Bus Stop Proximity (Child of Transportation)
  {
    title: 'Bus Stop Proximity',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'bus-stop-proximity',
    slugLock: true,
    parent: 415,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4415',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4416',
        doc: 415,
        url: '/community-amenities/transportation',
        label: 'Transportation',
      },
      {
        id: '67b0b8449a1e4304421b4417',
        doc: 417,
        url: '/community-amenities/transportation/bus-stop-proximity',
        label: 'Bus Stop Proximity',
      },
    ],
    _status: 'published',
  },
  // Taxi Stand (Child of Transportation)
  {
    title: 'Taxi Stand',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'taxi-stand',
    slugLock: true,
    parent: 415,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4418',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4419',
        doc: 415,
        url: '/community-amenities/transportation',
        label: 'Transportation',
      },
      {
        id: '67b0b8449a1e4304421b4420',
        doc: 418,
        url: '/community-amenities/transportation/taxi-stand',
        label: 'Taxi Stand',
      },
    ],
    _status: 'published',
  },
  // Car Share Parking (Child of Transportation)
  {
    title: 'Car Share Parking',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'car-share-parking',
    slugLock: true,
    parent: 415,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4421',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4422',
        doc: 415,
        url: '/community-amenities/transportation',
        label: 'Transportation',
      },
      {
        id: '67b0b8449a1e4304421b4423',
        doc: 419,
        url: '/community-amenities/transportation/car-share-parking',
        label: 'Car Share Parking',
      },
    ],
    _status: 'published',
  },
  // Education (Child of Community Amenities)
  {
    title: 'Education',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'education',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b4424',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b7de9a1e4304421b4425',
        doc: 420,
        url: '/community-amenities/education',
        label: 'Education',
      },
    ],
    _status: 'published',
  },
  // Schools Nearby (Child of Education)
  {
    title: 'Schools Nearby',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'schools-nearby',
    slugLock: true,
    parent: 420,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4426',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4427',
        doc: 420,
        url: '/community-amenities/education',
        label: 'Education',
      },
      {
        id: '67b0b8449a1e4304421b4428',
        doc: 421,
        url: '/community-amenities/education/schools-nearby',
        label: 'Schools Nearby',
      },
    ],
    _status: 'published',
  },
  // Universities (Child of Education)
  {
    title: 'Universities',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'universities',
    slugLock: true,
    parent: 420,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4429',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4430',
        doc: 420,
        url: '/community-amenities/education',
        label: 'Education',
      },
      {
        id: '67b0b8449a1e4304421b4431',
        doc: 422,
        url: '/community-amenities/education/universities',
        label: 'Universities',
      },
    ],
    _status: 'published',
  },
  // Nurseries (Child of Education)
  {
    title: 'Nurseries',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'nurseries',
    slugLock: true,
    parent: 420,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4432',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4433',
        doc: 420,
        url: '/community-amenities/education',
        label: 'Education',
      },
      {
        id: '67b0b8449a1e4304421b4434',
        doc: 423,
        url: '/community-amenities/education/nurseries',
        label: 'Nurseries',
      },
    ],
    _status: 'published',
  },
  // Worship (Child of Community Amenities)
  {
    title: 'Worship',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'worship',
    slugLock: true,
    parent: 400,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b4435',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b7de9a1e4304421b4436',
        doc: 424,
        url: '/community-amenities/worship',
        label: 'Worship',
      },
    ],
    _status: 'published',
  },
  // Mosques (Child of Worship)
  {
    title: 'Mosques',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'mosques',
    slugLock: true,
    parent: 424,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4437',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4438',
        doc: 424,
        url: '/community-amenities/worship',
        label: 'Worship',
      },
      {
        id: '67b0b8449a1e4304421b4439',
        doc: 425,
        url: '/community-amenities/worship/mosques',
        label: 'Mosques',
      },
    ],
    _status: 'published',
  },
  // Prayer Rooms (Child of Worship)
  {
    title: 'Prayer Rooms',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'prayer-rooms',
    slugLock: true,
    parent: 424,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4440',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4441',
        doc: 424,
        url: '/community-amenities/worship',
        label: 'Worship',
      },
      {
        id: '67b0b8449a1e4304421b4442',
        doc: 426,
        url: '/community-amenities/worship/prayer-rooms',
        label: 'Prayer Rooms',
      },
    ],
    _status: 'published',
  },
  // Churches (Child of Worship)
  {
    title: 'Churches',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'churches',
    slugLock: true,
    parent: 424,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4443',
        doc: 400,
        url: '/community-amenities',
        label: 'Community Amenities',
      },
      {
        id: '67b0b8449a1e4304421b4444',
        doc: 424,
        url: '/community-amenities/worship',
        label: 'Worship',
      },
      {
        id: '67b0b8449a1e4304421b4445',
        doc: 427,
        url: '/community-amenities/worship/churches',
        label: 'Churches',
      },
    ],
    _status: 'published',
  },
]
