import type { Contract } from '@payload-types'

type CreateContract = Omit<
  Contract,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockSalesContracts: CreateContract[] = [
  // Sales Contracts (Parent)
  {
    title: 'Sales Contracts',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:20:50.276Z',
    slug: 'sales-contracts',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f3',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
    ],
    _status: 'published',
  },
  // Outright Purchase (Child of Sales Contracts)
  {
    title: 'Outright Purchase',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:21:50.276Z',
    slug: 'outright-purchase',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f4',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43f5',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
    ],
    _status: 'published',
  },
  // Ready Property (Child of Outright Purchase)
  {
    title: 'Ready Property',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:22:50.276Z',
    slug: 'ready-property',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f6',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43f7',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b43f8',
        doc: 202,
        url: '/sales-contracts/outright-purchase/ready-property',
        label: 'Ready Property',
      },
    ],
    _status: 'published',
  },
  // Immediate Transfer (Child of Ready Property)
  {
    title: 'Immediate Transfer',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:23:50.276Z',
    slug: 'immediate-transfer',
    slugLock: true,
    parent: 202,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43f9',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43fa',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b43fb',
        doc: 202,
        url: '/sales-contracts/outright-purchase/ready-property',
        label: 'Ready Property',
      },
      {
        id: '67b0b8449a1e4304421b43fc',
        doc: 203,
        url: '/sales-contracts/outright-purchase/ready-property/immediate-transfer',
        label: 'Immediate Transfer',
      },
    ],
    _status: 'published',
  },
  // Delayed Transfer (Child of Ready Property)
  {
    title: 'Delayed Transfer',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:24:50.276Z',
    slug: 'delayed-transfer',
    slugLock: true,
    parent: 202,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43fd',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b43fe',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b43ff',
        doc: 202,
        url: '/sales-contracts/outright-purchase/ready-property',
        label: 'Ready Property',
      },
      {
        id: '67b0b8449a1e4304421b4400',
        doc: 204,
        url: '/sales-contracts/outright-purchase/ready-property/delayed-transfer',
        label: 'Delayed Transfer',
      },
    ],
    _status: 'published',
  },
  // Off-Plan Property (Child of Outright Purchase)
  {
    title: 'Off-Plan Property',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:25:50.276Z',
    slug: 'off-plan-property',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4401',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4402',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b4403',
        doc: 205,
        url: '/sales-contracts/outright-purchase/off-plan-property',
        label: 'Off-Plan Property',
      },
    ],
    _status: 'published',
  },
  // Under Construction (Child of Off-Plan Property)
  {
    title: 'Under Construction',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:26:50.276Z',
    slug: 'under-construction',
    slugLock: true,
    parent: 205,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4404',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4405',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b4406',
        doc: 205,
        url: '/sales-contracts/outright-purchase/off-plan-property',
        label: 'Off-Plan Property',
      },
      {
        id: '67b0b8449a1e4304421b4407',
        doc: 206,
        url: '/sales-contracts/outright-purchase/off-plan-property/under-construction',
        label: 'Under Construction',
      },
    ],
    _status: 'published',
  },
  // Pre-Launch (Child of Off-Plan Property)
  {
    title: 'Pre-Launch',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:27:50.276Z',
    slug: 'pre-launch',
    slugLock: true,
    parent: 205,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4408',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4409',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b440a',
        doc: 205,
        url: '/sales-contracts/outright-purchase/off-plan-property',
        label: 'Off-Plan Property',
      },
      {
        id: '67b0b8449a1e4304421b440b',
        doc: 207,
        url: '/sales-contracts/outright-purchase/off-plan-property/pre-launch',
        label: 'Pre-Launch',
      },
    ],
    _status: 'published',
  },
  // Launch Phase (Child of Off-Plan Property)
  {
    title: 'Launch Phase',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:28:50.276Z',
    slug: 'launch-phase',
    slugLock: true,
    parent: 205,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b440c',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b440d',
        doc: 201,
        url: '/sales-contracts/outright-purchase',
        label: 'Outright Purchase',
      },
      {
        id: '67b0b8449a1e4304421b440e',
        doc: 205,
        url: '/sales-contracts/outright-purchase/off-plan-property',
        label: 'Off-Plan Property',
      },
      {
        id: '67b0b8449a1e4304421b440f',
        doc: 208,
        url: '/sales-contracts/outright-purchase/off-plan-property/launch-phase',
        label: 'Launch Phase',
      },
    ],
    _status: 'published',
  },
  // Payment Plans (Child of Sales Contracts)
  {
    title: 'Payment Plans',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:29:50.276Z',
    slug: 'payment-plans',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4410',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4411',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
    ],
    _status: 'published',
  },
  // Standard Payment Plan (Child of Payment Plans)
  {
    title: 'Standard Payment Plan',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:30:50.276Z',
    slug: 'standard-payment-plan',
    slugLock: true,
    parent: 209,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4412',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4413',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b4414',
        doc: 210,
        url: '/sales-contracts/payment-plans/standard-payment-plan',
        label: 'Standard Payment Plan',
      },
    ],
    _status: 'published',
  },
  // Down Payment + Installments (Child of Standard Payment Plan)
  {
    title: 'Down Payment + Installments',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:31:50.276Z',
    slug: 'down-payment-installments',
    slugLock: true,
    parent: 210,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4415',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4416',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b4417',
        doc: 210,
        url: '/sales-contracts/payment-plans/standard-payment-plan',
        label: 'Standard Payment Plan',
      },
      {
        id: '67b0b8449a1e4304421b4418',
        doc: 211,
        url: '/sales-contracts/payment-plans/standard-payment-plan/down-payment-installments',
        label: 'Down Payment + Installments',
      },
    ],
    _status: 'published',
  },
  // Post-Handover Plan (Child of Standard Payment Plan)
  {
    title: 'Post-Handover Plan',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:32:50.276Z',
    slug: 'post-handover-plan',
    slugLock: true,
    parent: 210,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4419',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b441a',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b441b',
        doc: 210,
        url: '/sales-contracts/payment-plans/standard-payment-plan',
        label: 'Standard Payment Plan',
      },
      {
        id: '67b0b8449a1e4304421b441c',
        doc: 212,
        url: '/sales-contracts/payment-plans/standard-payment-plan/post-handover-plan',
        label: 'Post-Handover Plan',
      },
    ],
    _status: 'published',
  },
  // Developer Finance (Child of Payment Plans)
  {
    title: 'Developer Finance',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:33:50.276Z',
    slug: 'developer-finance',
    slugLock: true,
    parent: 209,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b441d',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b441e',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b441f',
        doc: 213,
        url: '/sales-contracts/payment-plans/developer-finance',
        label: 'Developer Finance',
      },
    ],
    _status: 'published',
  },
  // In-House Finance (Child of Developer Finance)
  {
    title: 'In-House Finance',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:34:50.276Z',
    slug: 'in-house-finance',
    slugLock: true,
    parent: 213,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4420',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4421',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b4422',
        doc: 213,
        url: '/sales-contracts/payment-plans/developer-finance',
        label: 'Developer Finance',
      },
      {
        id: '67b0b8449a1e4304421b4423',
        doc: 214,
        url: '/sales-contracts/payment-plans/developer-finance/in-house-finance',
        label: 'In-House Finance',
      },
    ],
    _status: 'published',
  },
  // Extended Payment Terms (Child of Developer Finance)
  {
    title: 'Extended Payment Terms',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:35:50.276Z',
    slug: 'extended-payment-terms',
    slugLock: true,
    parent: 213,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4424',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4425',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b4426',
        doc: 213,
        url: '/sales-contracts/payment-plans/developer-finance',
        label: 'Developer Finance',
      },
      {
        id: '67b0b8449a1e4304421b4427',
        doc: 215,
        url: '/sales-contracts/payment-plans/developer-finance/extended-payment-terms',
        label: 'Extended Payment Terms',
      },
    ],
    _status: 'published',
  },
  // Rent-to-Own (Child of Payment Plans)
  {
    title: 'Rent-to-Own',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:36:50.276Z',
    slug: 'rent-to-own',
    slugLock: true,
    parent: 209,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b4428',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4429',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b442a',
        doc: 216,
        url: '/sales-contracts/payment-plans/rent-to-own',
        label: 'Rent-to-Own',
      },
    ],
    _status: 'published',
  },
  // Standard Conversion (Child of Rent-to-Own)
  {
    title: 'Standard Conversion',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:37:50.276Z',
    slug: 'standard-conversion',
    slugLock: true,
    parent: 216,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b442b',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b442c',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b442d',
        doc: 216,
        url: '/sales-contracts/payment-plans/rent-to-own',
        label: 'Rent-to-Own',
      },
      {
        id: '67b0b8449a1e4304421b442e',
        doc: 217,
        url: '/sales-contracts/payment-plans/rent-to-own/standard-conversion',
        label: 'Standard Conversion',
      },
    ],
    _status: 'published',
  },
  // Flexible Terms (Child of Rent-to-Own)
  {
    title: 'Flexible Terms',
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:38:50.276Z',
    slug: 'flexible-terms',
    slugLock: true,
    parent: 216,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b442f',
        doc: 200,
        url: '/sales-contracts',
        label: 'Sales Contracts',
      },
      {
        id: '67b0b8449a1e4304421b4430',
        doc: 209,
        url: '/sales-contracts/payment-plans',
        label: 'Payment Plans',
      },
      {
        id: '67b0b8449a1e4304421b4431',
        doc: 216,
        url: '/sales-contracts/payment-plans/rent-to-own',
        label: 'Rent-to-Own',
      },
      {
        id: '67b0b8449a1e4304421b4432',
        doc: 218,
        url: '/sales-contracts/payment-plans/rent-to-own/flexible-terms',
        label: 'Flexible Terms',
      },
    ],
    _status: 'published',
  },
]
