import type { Classification } from '@payload-types'

type CreateClassification = Omit<
  Classification,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockLocationTypes: CreateClassification[] = [
  // Location Type (Parent)
  {
    title: 'Location Type',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:00:00.000Z',
    slug: 'location-type',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
    ],
    _status: 'published',
  },
  // Urban Classification (Parent)
  {
    title: 'Urban Classification',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:01:00.000Z',
    slug: 'urban-classification',
    slugLock: true,
    parent: 600,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '601-urban-classification',
        doc: 601,
        url: '/location-type/urban-classification',
        label: 'Urban Classification',
      },
    ],
    _status: 'published',
  },
  // City Center
  {
    title: 'City Center',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:02:00.000Z',
    slug: 'city-center',
    slugLock: true,
    parent: 601,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '601-urban-classification',
        doc: 601,
        url: '/location-type/urban-classification',
        label: 'Urban Classification',
      },
      {
        id: '602-city-center',
        doc: 602,
        url: '/location-type/urban-classification/city-center',
        label: 'City Center',
      },
    ],
    _status: 'published',
  },
  // Business District
  {
    title: 'Business District',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:03:00.000Z',
    slug: 'business-district',
    slugLock: true,
    parent: 601,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '601-urban-classification',
        doc: 601,
        url: '/location-type/urban-classification',
        label: 'Urban Classification',
      },
      {
        id: '603-business-district',
        doc: 603,
        url: '/location-type/urban-classification/business-district',
        label: 'Business District',
      },
    ],
    _status: 'published',
  },
  // Suburban Area
  {
    title: 'Suburban Area',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:04:00.000Z',
    slug: 'suburban-area',
    slugLock: true,
    parent: 601,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '601-urban-classification',
        doc: 601,
        url: '/location-type/urban-classification',
        label: 'Urban Classification',
      },
      {
        id: '604-suburban-area',
        doc: 604,
        url: '/location-type/urban-classification/suburban-area',
        label: 'Suburban Area',
      },
    ],
    _status: 'published',
  },
  // Industrial Area
  {
    title: 'Industrial Area',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:05:00.000Z',
    slug: 'industrial-area',
    slugLock: true,
    parent: 601,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '601-urban-classification',
        doc: 601,
        url: '/location-type/urban-classification',
        label: 'Urban Classification',
      },
      {
        id: '605-industrial-area',
        doc: 605,
        url: '/location-type/urban-classification/industrial-area',
        label: 'Industrial Area',
      },
    ],
    _status: 'published',
  },
  // Mixed Development
  {
    title: 'Mixed Development',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:06:00.000Z',
    slug: 'mixed-development',
    slugLock: true,
    parent: 601,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '601-urban-classification',
        doc: 601,
        url: '/location-type/urban-classification',
        label: 'Urban Classification',
      },
      {
        id: '606-mixed-development',
        doc: 606,
        url: '/location-type/urban-classification/mixed-development',
        label: 'Mixed Development',
      },
    ],
    _status: 'published',
  },
  // Accessibility (Parent)
  {
    title: 'Accessibility',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:07:00.000Z',
    slug: 'accessibility',
    slugLock: true,
    parent: 600,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '607-accessibility',
        doc: 607,
        url: '/location-type/accessibility',
        label: 'Accessibility',
      },
    ],
    _status: 'published',
  },
  // Metro Connected
  {
    title: 'Metro Connected',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:08:00.000Z',
    slug: 'metro-connected',
    slugLock: true,
    parent: 607,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '607-accessibility',
        doc: 607,
        url: '/location-type/accessibility',
        label: 'Accessibility',
      },
      {
        id: '608-metro-connected',
        doc: 608,
        url: '/location-type/accessibility/metro-connected',
        label: 'Metro Connected',
      },
    ],
    _status: 'published',
  },
  // Bus Connected
  {
    title: 'Bus Connected',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:09:00.000Z',
    slug: 'bus-connected',
    slugLock: true,
    parent: 607,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '607-accessibility',
        doc: 607,
        url: '/location-type/accessibility',
        label: 'Accessibility',
      },
      {
        id: '609-bus-connected',
        doc: 609,
        url: '/location-type/accessibility/bus-connected',
        label: 'Bus Connected',
      },
    ],
    _status: 'published',
  },
  // Car Dependent
  {
    title: 'Car Dependent',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:10:00.000Z',
    slug: 'car-dependent',
    slugLock: true,
    parent: 607,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '607-accessibility',
        doc: 607,
        url: '/location-type/accessibility',
        label: 'Accessibility',
      },
      {
        id: '610-car-dependent',
        doc: 610,
        url: '/location-type/accessibility/car-dependent',
        label: 'Car Dependent',
      },
    ],
    _status: 'published',
  },
  // Walk-friendly
  {
    title: 'Walk-friendly',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:11:00.000Z',
    slug: 'walk-friendly',
    slugLock: true,
    parent: 607,
    breadcrumbs: [
      {
        id: '600-location-type',
        doc: 600,
        url: '/location-type',
        label: 'Location Type',
      },
      {
        id: '607-accessibility',
        doc: 607,
        url: '/location-type/accessibility',
        label: 'Accessibility',
      },
      {
        id: '611-walk-friendly',
        doc: 611,
        url: '/location-type/accessibility/walk-friendly',
        label: 'Walk-friendly',
      },
    ],
    _status: 'published',
  },
]
