import type { Classification } from '@payload-types'

type CreateClassification = Omit<
  Classification,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockPropertyClasses: CreateClassification[] = [
  // Property Class (Root)
  {
    title: 'Property Class',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:00:00.000Z',
    slug: 'property-class',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e0',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
    ],
    _status: 'published',
  },
  // Luxury (Child of Property Class)
  {
    title: 'Luxury',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:01:00.000Z',
    slug: 'luxury',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e1',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f1',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
    ],
    _status: 'published',
  },
  // Premium (Child of Luxury)
  {
    title: 'Premium',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:02:00.000Z',
    slug: 'premium',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e2',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f2',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f3',
        doc: 202,
        url: '/property-classes/luxury/premium',
        label: 'Premium',
      },
    ],
    _status: 'published',
  },
  // Ultra Luxury (Child of Premium)
  {
    title: 'Ultra Luxury',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:03:00.000Z',
    slug: 'ultra-luxury',
    slugLock: true,
    parent: 202,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e3',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f4',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f5',
        doc: 202,
        url: '/property-classes/luxury/premium',
        label: 'Premium',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f6',
        doc: 203,
        url: '/property-classes/luxury/premium/ultra-luxury',
        label: 'Ultra Luxury',
      },
    ],
    _status: 'published',
  },
  // High-End Luxury (Child of Premium)
  {
    title: 'High-End Luxury',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:04:00.000Z',
    slug: 'high-end-luxury',
    slugLock: true,
    parent: 202,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e4',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f7',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f8',
        doc: 202,
        url: '/property-classes/luxury/premium',
        label: 'Premium',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1f9',
        doc: 204,
        url: '/property-classes/luxury/premium/high-end-luxury',
        label: 'High-End Luxury',
      },
    ],
    _status: 'published',
  },
  // Upper Luxury (Child of Luxury)
  {
    title: 'Upper Luxury',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:05:00.000Z',
    slug: 'upper-luxury',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e5',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1fa',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1fb',
        doc: 205,
        url: '/property-classes/luxury/upper-luxury',
        label: 'Upper Luxury',
      },
    ],
    _status: 'published',
  },
  // Modern Luxury (Child of Upper Luxury)
  {
    title: 'Modern Luxury',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:06:00.000Z',
    slug: 'modern-luxury',
    slugLock: true,
    parent: 205,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e6',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1fc',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1fd',
        doc: 205,
        url: '/property-classes/luxury/upper-luxury',
        label: 'Upper Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1fe',
        doc: 206,
        url: '/property-classes/luxury/upper-luxury/modern-luxury',
        label: 'Modern Luxury',
      },
    ],
    _status: 'published',
  },
  // Classic Luxury (Child of Upper Luxury)
  {
    title: 'Classic Luxury',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:07:00.000Z',
    slug: 'classic-luxury',
    slugLock: true,
    parent: 205,
    breadcrumbs: [
      {
        id: '65f1c1f1c1f1c1f1c1f1c1e7',
        doc: 200,
        url: '/property-classes',
        label: 'Property Class',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c1ff',
        doc: 201,
        url: '/property-classes/luxury',
        label: 'Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c200',
        doc: 205,
        url: '/property-classes/luxury/upper-luxury',
        label: 'Upper Luxury',
      },
      {
        id: '65f1c1f1c1f1c1f1c1f1c201',
        doc: 207,
        url: '/property-classes/luxury/upper-luxury/classic-luxury',
        label: 'Classic Luxury',
      },
    ],
    _status: 'published',
  },
]
