import type { Classification } from '@payload-types'

type CreateClassification = Omit<
  Classification,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const mockUsageTypes: CreateClassification[] = [
  // Usage Type (Parent)
  {
    title: 'Usage Type',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:00:00.000Z',
    slug: 'usage-type',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
    ],
    _status: 'published',
  },
  // Residential Purpose (First Level)
  {
    title: 'Residential Purpose',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:01:00.000Z',
    slug: 'residential-purpose',
    slugLock: true,
    parent: 300,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 301,
        url: '/usage-type/residential-purpose',
        label: 'Residential Purpose',
      },
    ],
    _status: 'published',
  },
  // Primary Residence
  {
    title: 'Primary Residence',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:02:00.000Z',
    slug: 'primary-residence',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 301,
        url: '/usage-type/residential-purpose',
        label: 'Residential Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f8',
        doc: 302,
        url: '/usage-type/residential-purpose/primary-residence',
        label: 'Primary Residence',
      },
    ],
    _status: 'published',
  },
  // Secondary Home
  {
    title: 'Secondary Home',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:03:00.000Z',
    slug: 'secondary-home',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 301,
        url: '/usage-type/residential-purpose',
        label: 'Residential Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f9',
        doc: 303,
        url: '/usage-type/residential-purpose/secondary-home',
        label: 'Secondary Home',
      },
    ],
    _status: 'published',
  },
  // Holiday Home
  {
    title: 'Holiday Home',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:04:00.000Z',
    slug: 'holiday-home',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 301,
        url: '/usage-type/residential-purpose',
        label: 'Residential Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fa',
        doc: 304,
        url: '/usage-type/residential-purpose/holiday-home',
        label: 'Holiday Home',
      },
    ],
    _status: 'published',
  },
  // Student Housing
  {
    title: 'Student Housing',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:05:00.000Z',
    slug: 'student-housing',
    slugLock: true,
    parent: 301,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f7',
        doc: 301,
        url: '/usage-type/residential-purpose',
        label: 'Residential Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fb',
        doc: 305,
        url: '/usage-type/residential-purpose/student-housing',
        label: 'Student Housing',
      },
    ],
    _status: 'published',
  },
  // Investment Purpose (First Level)
  {
    title: 'Investment Purpose',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:06:00.000Z',
    slug: 'investment-purpose',
    slugLock: true,
    parent: 300,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fc',
        doc: 306,
        url: '/usage-type/investment-purpose',
        label: 'Investment Purpose',
      },
    ],
    _status: 'published',
  },
  // Rental Income
  {
    title: 'Rental Income',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:07:00.000Z',
    slug: 'rental-income',
    slugLock: true,
    parent: 306,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fc',
        doc: 306,
        url: '/usage-type/investment-purpose',
        label: 'Investment Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fd',
        doc: 307,
        url: '/usage-type/investment-purpose/rental-income',
        label: 'Rental Income',
      },
    ],
    _status: 'published',
  },
  // Value Appreciation
  {
    title: 'Value Appreciation',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:08:00.000Z',
    slug: 'value-appreciation',
    slugLock: true,
    parent: 306,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fc',
        doc: 306,
        url: '/usage-type/investment-purpose',
        label: 'Investment Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fe',
        doc: 308,
        url: '/usage-type/investment-purpose/value-appreciation',
        label: 'Value Appreciation',
      },
    ],
    _status: 'published',
  },
  // Mixed Use
  {
    title: 'Mixed Use',
    description: null,
    image: null,
    icon: null,
    relatedDocs: [],
    meta: {
      title: null,
      description: null,
      image: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2024-01-01T00:09:00.000Z',
    slug: 'mixed-use',
    slugLock: true,
    parent: 306,
    breadcrumbs: [
      {
        id: '65f1c1a1e4b0a1b2c3d4e5f6',
        doc: 300,
        url: '/usage-type',
        label: 'Usage Type',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5fc',
        doc: 306,
        url: '/usage-type/investment-purpose',
        label: 'Investment Purpose',
      },
      {
        id: '65f1c1a1e4b0a1b2c3d4e5ff',
        doc: 309,
        url: '/usage-type/investment-purpose/mixed-use',
        label: 'Mixed Use',
      },
    ],
    _status: 'published',
  },
]
