import type { Amenity } from '@payload-types'

type CreateAmenity = Omit<
  Amenity,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const buildingAmenities: CreateAmenity[] = [
  // Building Amenities (Parent)
  {
    title: 'Building Amenities',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:17.675Z',
    slug: 'building-amenities',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b7b99a1e4304421b439b',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
    ],
    _status: 'published',
  },
  // Security (Child of Building Amenities)
  {
    title: 'Security',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:50:54.156Z',
    slug: 'security',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '67b0b7de9a1e4304421b43a0',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b7de9a1e4304421b43a1',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
    ],
    _status: 'published',
  },
  // CCTV Surveillance (Child of Security)
  {
    title: 'CCTV Surveillance',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:51:50.276Z',
    slug: 'cctv-surveillance',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8449a1e4304421b43a7',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b8449a1e4304421b43a8',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
      {
        id: '67b0b8449a1e4304421b43a9',
        doc: 102,
        url: '/building-amenities/security/cctv-surveillance',
        label: 'CCTV Surveillance',
      },
    ],
    _status: 'published',
  },
  // 24/7 Security (Child of Security)
  {
    title: '24/7 Security',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:10.276Z',
    slug: '24-7-security',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8649a1e4304421b43b1',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b8649a1e4304421b43b2',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
      {
        id: '67b0b8649a1e4304421b43b3',
        doc: 103,
        url: '/building-amenities/security/24-7-security',
        label: '24/7 Security',
      },
    ],
    _status: 'published',
  },
  // Access Control System (Child of Security)
  {
    title: 'Access Control System',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:30.276Z',
    slug: 'access-control-system',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8849a1e4304421b43b7',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b8849a1e4304421b43b8',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
      {
        id: '67b0b8849a1e4304421b43b9',
        doc: 104,
        url: '/building-amenities/security/access-control-system',
        label: 'Access Control System',
      },
    ],
    _status: 'published',
  },
  // Secure Parking (Child of Security)
  {
    title: 'Secure Parking',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:52:50.276Z',
    slug: 'secure-parking',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8a49a1e4304421b43c1',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b8a49a1e4304421b43c2',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
      {
        id: '67b0b8a49a1e4304421b43c3',
        doc: 105,
        url: '/building-amenities/security/secure-parking',
        label: 'Secure Parking',
      },
    ],
    _status: 'published',
  },
  // Security Desk (Child of Security)
  {
    title: 'Security Desk',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:10.276Z',
    slug: 'security-desk',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8c49a1e4304421b43c7',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b8c49a1e4304421b43c8',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
      {
        id: '67b0b8c49a1e4304421b43c9',
        doc: 106,
        url: '/building-amenities/security/security-desk',
        label: 'Security Desk',
      },
    ],
    _status: 'published',
  },
  // Intercom System (Child of Security)
  {
    title: 'Intercom System',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.276Z',
    slug: 'intercom-system',
    slugLock: true,
    parent: 101,
    breadcrumbs: [
      {
        id: '67b0b8e49a1e4304421b43d1',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b8e49a1e4304421b43d2',
        doc: 101,
        url: '/building-amenities/security',
        label: 'Security',
      },
      {
        id: '67b0b8e49a1e4304421b43d3',
        doc: 107,
        url: '/building-amenities/security/intercom-system',
        label: 'Intercom System',
      },
    ],
    _status: 'published',
  },
  // Parking (Child of Building Amenities)
  {
    title: 'Parking',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:50.276Z',
    slug: 'parking',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '67b0b9049a1e4304421b43d7',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9049a1e4304421b43d8',
        doc: 108,
        url: '/building-amenities/parking',
        label: 'Parking',
      },
    ],
    _status: 'published',
  },
  // Covered Parking (Child of Parking)
  {
    title: 'Covered Parking',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:10.276Z',
    slug: 'covered-parking',
    slugLock: true,
    parent: 108,
    breadcrumbs: [
      {
        id: '67b0b9249a1e4304421b43e1',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9249a1e4304421b43e2',
        doc: 108,
        url: '/building-amenities/parking',
        label: 'Parking',
      },
      {
        id: '67b0b9249a1e4304421b43e3',
        doc: 109,
        url: '/building-amenities/parking/covered-parking',
        label: 'Covered Parking',
      },
    ],
    _status: 'published',
  },
  // Visitor Parking (Child of Parking)
  {
    title: 'Visitor Parking',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:30.276Z',
    slug: 'visitor-parking',
    slugLock: true,
    parent: 108,
    breadcrumbs: [
      {
        id: '67b0b9449a1e4304421b43e7',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9449a1e4304421b43e8',
        doc: 108,
        url: '/building-amenities/parking',
        label: 'Parking',
      },
      {
        id: '67b0b9449a1e4304421b43e9',
        doc: 110,
        url: '/building-amenities/parking/visitor-parking',
        label: 'Visitor Parking',
      },
    ],
    _status: 'published',
  },
  // Electric Vehicle Charging (Child of Parking)
  {
    title: 'Electric Vehicle Charging',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:54:50.276Z',
    slug: 'electric-vehicle-charging',
    slugLock: true,
    parent: 108,
    breadcrumbs: [
      {
        id: '67b0b9649a1e4304421b43f1',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9649a1e4304421b43f2',
        doc: 108,
        url: '/building-amenities/parking',
        label: 'Parking',
      },
      {
        id: '67b0b9649a1e4304421b43f3',
        doc: 111,
        url: '/building-amenities/parking/electric-vehicle-charging',
        label: 'Electric Vehicle Charging',
      },
    ],
    _status: 'published',
  },
  // Valet Service (Child of Parking)
  {
    title: 'Valet Service',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:10.276Z',
    slug: 'valet-service',
    slugLock: true,
    parent: 108,
    breadcrumbs: [
      {
        id: '67b0b9849a1e4304421b43f7',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9849a1e4304421b43f8',
        doc: 108,
        url: '/building-amenities/parking',
        label: 'Parking',
      },
      {
        id: '67b0b9849a1e4304421b43f9',
        doc: 112,
        url: '/building-amenities/parking/valet-service',
        label: 'Valet Service',
      },
    ],
    _status: 'published',
  },
  // Bicycle Storage (Child of Parking)
  {
    title: 'Bicycle Storage',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:55:30.276Z',
    slug: 'bicycle-storage',
    slugLock: true,
    parent: 108,
    breadcrumbs: [
      {
        id: '67b0b9a49a1e4304421b4401',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9a49a1e4304421b4402',
        doc: 108,
        url: '/building-amenities/parking',
        label: 'Parking',
      },
      {
        id: '67b0b9a49a1e4304421b4403',
        doc: 113,
        url: '/building-amenities/parking/bicycle-storage',
        label: 'Bicycle Storage',
      },
    ],
    _status: 'published',
  },
  // Facilities (Child of Building Amenities)
  {
    title: 'Facilities',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:10.276Z',
    slug: 'facilities',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '67b0b9c49a1e4304421b4407',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9c49a1e4304421b4408',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
    ],
    _status: 'published',
  },
  // Swimming Pool (Child of Facilities)
  {
    title: 'Swimming Pool',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:30.276Z',
    slug: 'swimming-pool',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0b9e49a1e4304421b4411',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0b9e49a1e4304421b4412',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0b9e49a1e4304421b4413',
        doc: 115,
        url: '/building-amenities/facilities/swimming-pool',
        label: 'Swimming Pool',
      },
    ],
    _status: 'published',
  },
  // Adult Pool (Child of Swimming Pool)
  {
    title: 'Adult Pool',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:56:50.276Z',
    slug: 'adult-pool',
    slugLock: true,
    parent: 115,
    breadcrumbs: [
      {
        id: '67b0ba049a1e4304421b4417',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0ba049a1e4304421b4418',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0ba049a1e4304421b4419',
        doc: 115,
        url: '/building-amenities/facilities/swimming-pool',
        label: 'Swimming Pool',
      },
      {
        id: '67b0ba049a1e4304421b4420',
        doc: 116,
        url: '/building-amenities/facilities/swimming-pool/adult-pool',
        label: 'Adult Pool',
      },
    ],
    _status: 'published',
  },
  // Children's Pool (Child of Swimming Pool)
  {
    title: "Children's Pool",
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:57:10.276Z',
    slug: 'childrens-pool',
    slugLock: true,
    parent: 115,
    breadcrumbs: [
      {
        id: '67b0ba249a1e4304421b4421',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0ba249a1e4304421b4422',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0ba249a1e4304421b4423',
        doc: 115,
        url: '/building-amenities/facilities/swimming-pool',
        label: 'Swimming Pool',
      },
      {
        id: '67b0ba249a1e4304421b4424',
        doc: 117,
        url: '/building-amenities/facilities/swimming-pool/childrens-pool',
        label: "Children's Pool",
      },
    ],
    _status: 'published',
  },
  // Temperature Controlled Pool (Child of Swimming Pool)
  {
    title: 'Temperature Controlled Pool',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:57:30.276Z',
    slug: 'temperature-controlled-pool',
    slugLock: true,
    parent: 115,
    breadcrumbs: [
      {
        id: '67b0ba449a1e4304421b4425',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0ba449a1e4304421b4426',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0ba449a1e4304421b4427',
        doc: 115,
        url: '/building-amenities/facilities/swimming-pool',
        label: 'Swimming Pool',
      },
      {
        id: '67b0ba449a1e4304421b4428',
        doc: 118,
        url: '/building-amenities/facilities/swimming-pool/temperature-controlled-pool',
        label: 'Temperature Controlled Pool',
      },
    ],
    _status: 'published',
  },
  // Infinity Pool (Child of Swimming Pool)
  {
    title: 'Infinity Pool',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:57:50.276Z',
    slug: 'infinity-pool',
    slugLock: true,
    parent: 115,
    breadcrumbs: [
      {
        id: '67b0ba649a1e4304421b4429',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0ba649a1e4304421b4430',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0ba649a1e4304421b4431',
        doc: 115,
        url: '/building-amenities/facilities/swimming-pool',
        label: 'Swimming Pool',
      },
      {
        id: '67b0ba649a1e4304421b4432',
        doc: 119,
        url: '/building-amenities/facilities/swimming-pool/infinity-pool',
        label: 'Infinity Pool',
      },
    ],
    _status: 'published',
  },
  // Fitness Center (Child of Facilities)
  {
    title: 'Fitness Center',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:58:10.276Z',
    slug: 'fitness-center',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0ba849a1e4304421b4433',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0ba849a1e4304421b4434',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0ba849a1e4304421b4435',
        doc: 120,
        url: '/building-amenities/facilities/fitness-center',
        label: 'Fitness Center',
      },
    ],
    _status: 'published',
  },
  // Gym Equipment (Child of Fitness Center)
  {
    title: 'Gym Equipment',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:58:30.276Z',
    slug: 'gym-equipment',
    slugLock: true,
    parent: 120,
    breadcrumbs: [
      {
        id: '67b0baa49a1e4304421b4437',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0baa49a1e4304421b4438',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0baa49a1e4304421b4439',
        doc: 120,
        url: '/building-amenities/facilities/fitness-center',
        label: 'Fitness Center',
      },
      {
        id: '67b0baa49a1e4304421b4440',
        doc: 121,
        url: '/building-amenities/facilities/fitness-center/gym-equipment',
        label: 'Gym Equipment',
      },
    ],
    _status: 'published',
  },
  // Yoga Room (Child of Fitness Center)
  {
    title: 'Yoga Room',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:58:50.276Z',
    slug: 'yoga-room',
    slugLock: true,
    parent: 120,
    breadcrumbs: [
      {
        id: '67b0bac49a1e4304421b4441',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bac49a1e4304421b4442',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bac49a1e4304421b4443',
        doc: 120,
        url: '/building-amenities/facilities/fitness-center',
        label: 'Fitness Center',
      },
      {
        id: '67b0bac49a1e4304421b4444',
        doc: 122,
        url: '/building-amenities/facilities/fitness-center/yoga-room',
        label: 'Yoga Room',
      },
    ],
    _status: 'published',
  },
  // Personal Training Area (Child of Fitness Center)
  {
    title: 'Personal Training Area',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:10.276Z',
    slug: 'personal-training-area',
    slugLock: true,
    parent: 120,
    breadcrumbs: [
      {
        id: '67b0bae49a1e4304421b4445',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bae49a1e4304421b4446',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bae49a1e4304421b4447',
        doc: 120,
        url: '/building-amenities/facilities/fitness-center',
        label: 'Fitness Center',
      },
      {
        id: '67b0bae49a1e4304421b4448',
        doc: 123,
        url: '/building-amenities/facilities/fitness-center/personal-training-area',
        label: 'Personal Training Area',
      },
    ],
    _status: 'published',
  },
  // Recreation (Child of Facilities)
  {
    title: 'Recreation',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:30.276Z',
    slug: 'recreation',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0bb049a1e4304421b4449',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bb049a1e4304421b4450',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bb049a1e4304421b4451',
        doc: 124,
        url: '/building-amenities/facilities/recreation',
        label: 'Recreation',
      },
    ],
    _status: 'published',
  },
  // Children's Play Area (Child of Recreation)
  {
    title: "Children's Play Area",
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:59:50.276Z',
    slug: 'childrens-play-area',
    slugLock: true,
    parent: 124,
    breadcrumbs: [
      {
        id: '67b0bb249a1e4304421b4452',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bb249a1e4304421b4453',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bb249a1e4304421b4454',
        doc: 124,
        url: '/building-amenities/facilities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0bb249a1e4304421b4455',
        doc: 125,
        url: '/building-amenities/facilities/recreation/childrens-play-area',
        label: "Children's Play Area",
      },
    ],
    _status: 'published',
  },
  // Games Room (Child of Recreation)
  {
    title: 'Games Room',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:10.276Z',
    slug: 'games-room',
    slugLock: true,
    parent: 124,
    breadcrumbs: [
      {
        id: '67b0bb449a1e4304421b4456',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bb449a1e4304421b4457',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bb449a1e4304421b4458',
        doc: 124,
        url: '/building-amenities/facilities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0bb449a1e4304421b4459',
        doc: 126,
        url: '/building-amenities/facilities/recreation/games-room',
        label: 'Games Room',
      },
    ],
    _status: 'published',
  },
  // Community Room (Child of Recreation)
  {
    title: 'Community Room',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:30.276Z',
    slug: 'community-room',
    slugLock: true,
    parent: 124,
    breadcrumbs: [
      {
        id: '67b0bb649a1e4304421b4460',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bb649a1e4304421b4461',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bb649a1e4304421b4462',
        doc: 124,
        url: '/building-amenities/facilities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0bb649a1e4304421b4463',
        doc: 127,
        url: '/building-amenities/facilities/recreation/community-room',
        label: 'Community Room',
      },
    ],
    _status: 'published',
  },
  // BBQ Area (Child of Recreation)
  {
    title: 'BBQ Area',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:00:50.276Z',
    slug: 'bbq-area',
    slugLock: true,
    parent: 124,
    breadcrumbs: [
      {
        id: '67b0bb849a1e4304421b4464',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bb849a1e4304421b4465',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bb849a1e4304421b4466',
        doc: 124,
        url: '/building-amenities/facilities/recreation',
        label: 'Recreation',
      },
      {
        id: '67b0bb849a1e4304421b4467',
        doc: 128,
        url: '/building-amenities/facilities/recreation/bbq-area',
        label: 'BBQ Area',
      },
    ],
    _status: 'published',
  },
  // Wellness (Child of Facilities)
  {
    title: 'Wellness',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:01:10.276Z',
    slug: 'wellness',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0bba49a1e4304421b4468',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bba49a1e4304421b4469',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bba49a1e4304421b4470',
        doc: 129,
        url: '/building-amenities/facilities/wellness',
        label: 'Wellness',
      },
    ],
    _status: 'published',
  },
  // Sauna (Child of Wellness)
  {
    title: 'Sauna',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:01:30.276Z',
    slug: 'sauna',
    slugLock: true,
    parent: 129,
    breadcrumbs: [
      {
        id: '67b0bbc49a1e4304421b4471',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bbc49a1e4304421b4472',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bbc49a1e4304421b4473',
        doc: 129,
        url: '/building-amenities/facilities/wellness',
        label: 'Wellness',
      },
      {
        id: '67b0bbc49a1e4304421b4474',
        doc: 130,
        url: '/building-amenities/facilities/wellness/sauna',
        label: 'Sauna',
      },
    ],
    _status: 'published',
  },
  // Steam Room (Child of Wellness)
  {
    title: 'Steam Room',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:01:50.276Z',
    slug: 'steam-room',
    slugLock: true,
    parent: 129,
    breadcrumbs: [
      {
        id: '67b0bbe49a1e4304421b4475',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bbe49a1e4304421b4476',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bbe49a1e4304421b4477',
        doc: 129,
        url: '/building-amenities/facilities/wellness',
        label: 'Wellness',
      },
      {
        id: '67b0bbe49a1e4304421b4478',
        doc: 131,
        url: '/building-amenities/facilities/wellness/steam-room',
        label: 'Steam Room',
      },
    ],
    _status: 'published',
  },
  // Spa Facilities (Child of Wellness)
  {
    title: 'Spa Facilities',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:02:10.276Z',
    slug: 'spa-facilities',
    slugLock: true,
    parent: 129,
    breadcrumbs: [
      {
        id: '67b0bc049a1e4304421b4479',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bc049a1e4304421b4480',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bc049a1e4304421b4481',
        doc: 129,
        url: '/building-amenities/facilities/wellness',
        label: 'Wellness',
      },
      {
        id: '67b0bc049a1e4304421b4482',
        doc: 132,
        url: '/building-amenities/facilities/wellness/spa-facilities',
        label: 'Spa Facilities',
      },
    ],
    _status: 'published',
  },
  // Business (Child of Facilities)
  {
    title: 'Business',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:02:30.276Z',
    slug: 'business',
    slugLock: true,
    parent: 114,
    breadcrumbs: [
      {
        id: '67b0bc249a1e4304421b4483',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bc249a1e4304421b4484',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bc249a1e4304421b4485',
        doc: 133,
        url: '/building-amenities/facilities/business',
        label: 'Business',
      },
    ],
    _status: 'published',
  },
  // Co-working Space (Child of Business)
  {
    title: 'Co-working Space',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:02:50.276Z',
    slug: 'co-working-space',
    slugLock: true,
    parent: 133,
    breadcrumbs: [
      {
        id: '67b0bc449a1e4304421b4486',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bc449a1e4304421b4487',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bc449a1e4304421b4488',
        doc: 133,
        url: '/building-amenities/facilities/business',
        label: 'Business',
      },
      {
        id: '67b0bc449a1e4304421b4489',
        doc: 134,
        url: '/building-amenities/facilities/business/co-working-space',
        label: 'Co-working Space',
      },
    ],
    _status: 'published',
  },
  // Meeting Room (Child of Business)
  {
    title: 'Meeting Room',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:03:10.276Z',
    slug: 'meeting-room',
    slugLock: true,
    parent: 133,
    breadcrumbs: [
      {
        id: '67b0bc649a1e4304421b4490',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bc649a1e4304421b4491',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bc649a1e4304421b4492',
        doc: 133,
        url: '/building-amenities/facilities/business',
        label: 'Business',
      },
      {
        id: '67b0bc649a1e4304421b4493',
        doc: 135,
        url: '/building-amenities/facilities/business/meeting-room',
        label: 'Meeting Room',
      },
    ],
    _status: 'published',
  },
  // Business Center (Child of Business)
  {
    title: 'Business Center',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:03:30.276Z',
    slug: 'business-center',
    slugLock: true,
    parent: 133,
    breadcrumbs: [
      {
        id: '67b0bc849a1e4304421b4494',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bc849a1e4304421b4495',
        doc: 114,
        url: '/building-amenities/facilities',
        label: 'Facilities',
      },
      {
        id: '67b0bc849a1e4304421b4496',
        doc: 133,
        url: '/building-amenities/facilities/business',
        label: 'Business',
      },
      {
        id: '67b0bc849a1e4304421b4497',
        doc: 136,
        url: '/building-amenities/facilities/business/business-center',
        label: 'Business Center',
      },
    ],
    _status: 'published',
  },
  // Maintenance (Child of Building Amenities)
  {
    title: 'Maintenance',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:03:50.276Z',
    slug: 'maintenance',
    slugLock: true,
    parent: 100,
    breadcrumbs: [
      {
        id: '67b0bca49a1e4304421b4498',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bca49a1e4304421b4499',
        doc: 137,
        url: '/building-amenities/maintenance',
        label: 'Maintenance',
      },
    ],
    _status: 'published',
  },
  // 24/7 Maintenance (Child of Maintenance)
  {
    title: '24/7 Maintenance',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:04:10.276Z',
    slug: '24-7-maintenance',
    slugLock: true,
    parent: 137,
    breadcrumbs: [
      {
        id: '67b0bcc49a1e4304421b4500',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bcc49a1e4304421b4501',
        doc: 137,
        url: '/building-amenities/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0bcc49a1e4304421b4502',
        doc: 138,
        url: '/building-amenities/maintenance/24-7-maintenance',
        label: '24/7 Maintenance',
      },
    ],
    _status: 'published',
  },
  // Waste Management (Child of Maintenance)
  {
    title: 'Waste Management',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:04:30.276Z',
    slug: 'waste-management',
    slugLock: true,
    parent: 137,
    breadcrumbs: [
      {
        id: '67b0bce49a1e4304421b4503',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bce49a1e4304421b4504',
        doc: 137,
        url: '/building-amenities/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0bce49a1e4304421b4505',
        doc: 139,
        url: '/building-amenities/maintenance/waste-management',
        label: 'Waste Management',
      },
    ],
    _status: 'published',
  },
  // Cleaning Services (Child of Maintenance)
  {
    title: 'Cleaning Services',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:04:50.276Z',
    slug: 'cleaning-services',
    slugLock: true,
    parent: 137,
    breadcrumbs: [
      {
        id: '67b0bd049a1e4304421b4506',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bd049a1e4304421b4507',
        doc: 137,
        url: '/building-amenities/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0bd049a1e4304421b4508',
        doc: 140,
        url: '/building-amenities/maintenance/cleaning-services',
        label: 'Cleaning Services',
      },
    ],
    _status: 'published',
  },
  // Building Management Office (Child of Maintenance)
  {
    title: 'Building Management Office',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T16:05:10.276Z',
    slug: 'building-management-office',
    slugLock: true,
    parent: 137,
    breadcrumbs: [
      {
        id: '67b0bd249a1e4304421b4509',
        doc: 100,
        url: '/building-amenities',
        label: 'Building Amenities',
      },
      {
        id: '67b0bd249a1e4304421b4510',
        doc: 137,
        url: '/building-amenities/maintenance',
        label: 'Maintenance',
      },
      {
        id: '67b0bd249a1e4304421b4511',
        doc: 141,
        url: '/building-amenities/maintenance/building-management-office',
        label: 'Building Management Office',
      },
    ],
    _status: 'published',
  },
]
