import type { Amenity } from '@payload-types'

type CreateAmenity = Omit<
  Amenity,
  'id' | 'createdAt' | 'updatedAt' | 'properties'
>

export const unitAmenities: CreateAmenity[] = [
  // Unit Amenities (Parent)
  {
    title: 'Unit Amenities',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:08.351Z',
    slug: 'unit-amenities',
    slugLock: true,
    parent: null,
    breadcrumbs: [
      {
        id: '67b0b8649a1e4304421b43ae',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
    ],
    _status: 'published',
  },
  // Climate Control (Child of Unit Amenities)
  {
    title: 'Climate Control',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'climate-control',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b43b5',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b87a9a1e4304421b43b6',
        doc: 201,
        url: '/unit-amenities/climate-control',
        label: 'Climate Control',
      },
    ],
    _status: 'published',
  },
  // Central Air Conditioning
  {
    title: 'Central Air Conditioning',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'central-air-conditioning',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43ba',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43bb',
        doc: 201,
        url: '/unit-amenities/climate-control',
        label: 'Climate Control',
      },
      {
        id: '67b0b8899a1e4304421b43bc',
        doc: 202,
        url: '/unit-amenities/climate-control/central-air-conditioning',
        label: 'Central Air Conditioning',
      },
    ],
    _status: 'published',
  },
  // Split AC Units
  {
    title: 'Split AC Units',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'split-ac-units',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43bd',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43be',
        doc: 201,
        url: '/unit-amenities/climate-control',
        label: 'Climate Control',
      },
      {
        id: '67b0b8899a1e4304421b43bf',
        doc: 203,
        url: '/unit-amenities/climate-control/split-ac-units',
        label: 'Split AC Units',
      },
    ],
    _status: 'published',
  },
  // Temperature Control
  {
    title: 'Temperature Control',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'temperature-control',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43c0',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43c1',
        doc: 201,
        url: '/unit-amenities/climate-control',
        label: 'Climate Control',
      },
      {
        id: '67b0b8899a1e4304421b43c2',
        doc: 204,
        url: '/unit-amenities/climate-control/temperature-control',
        label: 'Temperature Control',
      },
    ],
    _status: 'published',
  },
  // Air Purification System
  {
    title: 'Air Purification System',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'air-purification-system',
    slugLock: true,
    parent: 201,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43c3',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43c4',
        doc: 201,
        url: '/unit-amenities/climate-control',
        label: 'Climate Control',
      },
      {
        id: '67b0b8899a1e4304421b43c5',
        doc: 205,
        url: '/unit-amenities/climate-control/air-purification-system',
        label: 'Air Purification System',
      },
    ],
    _status: 'published',
  },
  // Kitchen (Child of Unit Amenities)
  {
    title: 'Kitchen',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'kitchen',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b43c6',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b87a9a1e4304421b43c7',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
    ],
    _status: 'published',
  },
  // Built-in Appliances
  {
    title: 'Built-in Appliances',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'built-in-appliances',
    slugLock: true,
    parent: 206,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43c8',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43c9',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43ca',
        doc: 207,
        url: '/unit-amenities/kitchen/built-in-appliances',
        label: 'Built-in Appliances',
      },
    ],
    _status: 'published',
  },
  // Refrigerator
  {
    title: 'Refrigerator',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'refrigerator',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43cb',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43cc',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43cd',
        doc: 207,
        url: '/unit-amenities/kitchen/built-in-appliances',
        label: 'Built-in Appliances',
      },
      {
        id: '67b0b8899a1e4304421b43ce',
        doc: 208,
        url: '/unit-amenities/kitchen/built-in-appliances/refrigerator',
        label: 'Refrigerator',
      },
    ],
    _status: 'published',
  },
  // Dishwasher
  {
    title: 'Dishwasher',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'dishwasher',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43cf',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43d0',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43d1',
        doc: 207,
        url: '/unit-amenities/kitchen/built-in-appliances',
        label: 'Built-in Appliances',
      },
      {
        id: '67b0b8899a1e4304421b43d2',
        doc: 209,
        url: '/unit-amenities/kitchen/built-in-appliances/dishwasher',
        label: 'Dishwasher',
      },
    ],
    _status: 'published',
  },
  // Microwave
  {
    title: 'Microwave',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'microwave',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43d3',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43d4',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43d5',
        doc: 207,
        url: '/unit-amenities/kitchen/built-in-appliances',
        label: 'Built-in Appliances',
      },
      {
        id: '67b0b8899a1e4304421b43d6',
        doc: 210,
        url: '/unit-amenities/kitchen/built-in-appliances/microwave',
        label: 'Microwave',
      },
    ],
    _status: 'published',
  },
  // Oven
  {
    title: 'Oven',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'oven',
    slugLock: true,
    parent: 207,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43d7',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43d8',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43d9',
        doc: 207,
        url: '/unit-amenities/kitchen/built-in-appliances',
        label: 'Built-in Appliances',
      },
      {
        id: '67b0b8899a1e4304421b43da',
        doc: 211,
        url: '/unit-amenities/kitchen/built-in-appliances/oven',
        label: 'Oven',
      },
    ],
    _status: 'published',
  },
  // Kitchen Hood
  {
    title: 'Kitchen Hood',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'kitchen-hood',
    slugLock: true,
    parent: 206,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43db',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43dc',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43dd',
        doc: 212,
        url: '/unit-amenities/kitchen/kitchen-hood',
        label: 'Kitchen Hood',
      },
    ],
    _status: 'published',
  },
  // Granite/Quartz Countertops
  {
    title: 'Granite/Quartz Countertops',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'granite-quartz-countertops',
    slugLock: true,
    parent: 206,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43de',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43df',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43e0',
        doc: 213,
        url: '/unit-amenities/kitchen/granite-quartz-countertops',
        label: 'Granite/Quartz Countertops',
      },
    ],
    _status: 'published',
  },
  // Storage Solutions
  {
    title: 'Storage Solutions',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'storage-solutions',
    slugLock: true,
    parent: 206,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43e1',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43e2',
        doc: 206,
        url: '/unit-amenities/kitchen',
        label: 'Kitchen',
      },
      {
        id: '67b0b8899a1e4304421b43e3',
        doc: 214,
        url: '/unit-amenities/kitchen/storage-solutions',
        label: 'Storage Solutions',
      },
    ],
    _status: 'published',
  },
  // Technology (Child of Unit Amenities)
  {
    title: 'Technology',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'technology',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b43e4',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b87a9a1e4304421b43e5',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
    ],
    _status: 'published',
  },
  // High-speed Internet Ready
  {
    title: 'High-speed Internet Ready',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'high-speed-internet-ready',
    slugLock: true,
    parent: 215,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43e6',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43e7',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43e8',
        doc: 216,
        url: '/unit-amenities/technology/high-speed-internet-ready',
        label: 'High-speed Internet Ready',
      },
    ],
    _status: 'published',
  },
  // Smart Home Features
  {
    title: 'Smart Home Features',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'smart-home-features',
    slugLock: true,
    parent: 215,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43e9',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43ea',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43eb',
        doc: 217,
        url: '/unit-amenities/technology/smart-home-features',
        label: 'Smart Home Features',
      },
    ],
    _status: 'published',
  },
  // Smart Lighting
  {
    title: 'Smart Lighting',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'smart-lighting',
    slugLock: true,
    parent: 217,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43ec',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43ed',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43ee',
        doc: 217,
        url: '/unit-amenities/technology/smart-home-features',
        label: 'Smart Home Features',
      },
      {
        id: '67b0b8899a1e4304421b43ef',
        doc: 218,
        url: '/unit-amenities/technology/smart-home-features/smart-lighting',
        label: 'Smart Lighting',
      },
    ],
    _status: 'published',
  },
  // Smart Thermostats
  {
    title: 'Smart Thermostats',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'smart-thermostats',
    slugLock: true,
    parent: 217,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43f0',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43f1',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43f2',
        doc: 217,
        url: '/unit-amenities/technology/smart-home-features',
        label: 'Smart Home Features',
      },
      {
        id: '67b0b8899a1e4304421b43f3',
        doc: 219,
        url: '/unit-amenities/technology/smart-home-features/smart-thermostats',
        label: 'Smart Thermostats',
      },
    ],
    _status: 'published',
  },
  // Smart Locks
  {
    title: 'Smart Locks',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'smart-locks',
    slugLock: true,
    parent: 217,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43f4',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43f5',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43f6',
        doc: 217,
        url: '/unit-amenities/technology/smart-home-features',
        label: 'Smart Home Features',
      },
      {
        id: '67b0b8899a1e4304421b43f7',
        doc: 220,
        url: '/unit-amenities/technology/smart-home-features/smart-locks',
        label: 'Smart Locks',
      },
    ],
    _status: 'published',
  },
  // Satellite/Cable TV Ready
  {
    title: 'Satellite/Cable TV Ready',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'satellite-cable-tv-ready',
    slugLock: true,
    parent: 215,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43f8',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43f9',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43fa',
        doc: 221,
        url: '/unit-amenities/technology/satellite-cable-tv-ready',
        label: 'Satellite/Cable TV Ready',
      },
    ],
    _status: 'published',
  },
  // USB Charging Ports
  {
    title: 'USB Charging Ports',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'usb-charging-ports',
    slugLock: true,
    parent: 215,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b43fb',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b43fc',
        doc: 215,
        url: '/unit-amenities/technology',
        label: 'Technology',
      },
      {
        id: '67b0b8899a1e4304421b43fd',
        doc: 222,
        url: '/unit-amenities/technology/usb-charging-ports',
        label: 'USB Charging Ports',
      },
    ],
    _status: 'published',
  },
  // Interior Features (Child of Unit Amenities)
  {
    title: 'Interior Features',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'interior-features',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b43fe',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b87a9a1e4304421b43ff',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
    ],
    _status: 'published',
  },
  // Built-in Wardrobes
  {
    title: 'Built-in Wardrobes',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'built-in-wardrobes',
    slugLock: true,
    parent: 223,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4400',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4401',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
      {
        id: '67b0b8899a1e4304421b4402',
        doc: 224,
        url: '/unit-amenities/interior-features/built-in-wardrobes',
        label: 'Built-in Wardrobes',
      },
    ],
    _status: 'published',
  },
  // Floor-to-Ceiling Windows
  {
    title: 'Floor-to-Ceiling Windows',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'floor-to-ceiling-windows',
    slugLock: true,
    parent: 223,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4403',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4404',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
      {
        id: '67b0b8899a1e4304421b4405',
        doc: 225,
        url: '/unit-amenities/interior-features/floor-to-ceiling-windows',
        label: 'Floor-to-Ceiling Windows',
      },
    ],
    _status: 'published',
  },
  // Double Glazed Windows
  {
    title: 'Double Glazed Windows',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'double-glazed-windows',
    slugLock: true,
    parent: 223,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4406',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4407',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
      {
        id: '67b0b8899a1e4304421b4408',
        doc: 226,
        url: '/unit-amenities/interior-features/double-glazed-windows',
        label: 'Double Glazed Windows',
      },
    ],
    _status: 'published',
  },
  // Tiled/Wooden Flooring
  {
    title: 'Tiled/Wooden Flooring',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'tiled-wooden-flooring',
    slugLock: true,
    parent: 223,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4409',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b440a',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
      {
        id: '67b0b8899a1e4304421b440b',
        doc: 227,
        url: '/unit-amenities/interior-features/tiled-wooden-flooring',
        label: 'Tiled/Wooden Flooring',
      },
    ],
    _status: 'published',
  },
  // False Ceiling
  {
    title: 'False Ceiling',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'false-ceiling',
    slugLock: true,
    parent: 223,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b440c',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b440d',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
      {
        id: '67b0b8899a1e4304421b440e',
        doc: 228,
        url: '/unit-amenities/interior-features/false-ceiling',
        label: 'False Ceiling',
      },
    ],
    _status: 'published',
  },
  // LED Lighting
  {
    title: 'LED Lighting',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'led-lighting',
    slugLock: true,
    parent: 223,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b440f',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4410',
        doc: 223,
        url: '/unit-amenities/interior-features',
        label: 'Interior Features',
      },
      {
        id: '67b0b8899a1e4304421b4411',
        doc: 229,
        url: '/unit-amenities/interior-features/led-lighting',
        label: 'LED Lighting',
      },
    ],
    _status: 'published',
  },
  // Laundry (Child of Unit Amenities)
  {
    title: 'Laundry',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'laundry',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b4412',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b87a9a1e4304421b4413',
        doc: 230,
        url: '/unit-amenities/laundry',
        label: 'Laundry',
      },
    ],
    _status: 'published',
  },
  // Washer/Dryer
  {
    title: 'Washer/Dryer',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'washer-dryer',
    slugLock: true,
    parent: 230,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4414',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4415',
        doc: 230,
        url: '/unit-amenities/laundry',
        label: 'Laundry',
      },
      {
        id: '67b0b8899a1e4304421b4416',
        doc: 231,
        url: '/unit-amenities/laundry/washer-dryer',
        label: 'Washer/Dryer',
      },
    ],
    _status: 'published',
  },
  // Separate Laundry Room
  {
    title: 'Separate Laundry Room',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'separate-laundry-room',
    slugLock: true,
    parent: 230,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4417',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4418',
        doc: 230,
        url: '/unit-amenities/laundry',
        label: 'Laundry',
      },
      {
        id: '67b0b8899a1e4304421b4419',
        doc: 232,
        url: '/unit-amenities/laundry/separate-laundry-room',
        label: 'Separate Laundry Room',
      },
    ],
    _status: 'published',
  },
  // Built-in Laundry Facilities
  {
    title: 'Built-in Laundry Facilities',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'built-in-laundry-facilities',
    slugLock: true,
    parent: 230,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b441a',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b441b',
        doc: 230,
        url: '/unit-amenities/laundry',
        label: 'Laundry',
      },
      {
        id: '67b0b8899a1e4304421b441c',
        doc: 233,
        url: '/unit-amenities/laundry/built-in-laundry-facilities',
        label: 'Built-in Laundry Facilities',
      },
    ],
    _status: 'published',
  },
  // Common Laundry Area
  {
    title: 'Common Laundry Area',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'common-laundry-area',
    slugLock: true,
    parent: 230,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b441d',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b441e',
        doc: 230,
        url: '/unit-amenities/laundry',
        label: 'Laundry',
      },
      {
        id: '67b0b8899a1e4304421b441f',
        doc: 234,
        url: '/unit-amenities/laundry/common-laundry-area',
        label: 'Common Laundry Area',
      },
    ],
    _status: 'published',
  },
  // Outdoor Space (Child of Unit Amenities)
  {
    title: 'Outdoor Space',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:30.807Z',
    slug: 'outdoor-space',
    slugLock: true,
    parent: 200,
    breadcrumbs: [
      {
        id: '67b0b87a9a1e4304421b4420',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b87a9a1e4304421b4421',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
    ],
    _status: 'published',
  },
  // Balcony/Terrace
  {
    title: 'Balcony/Terrace',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'balcony-terrace',
    slugLock: true,
    parent: 235,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4422',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4423',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b4424',
        doc: 236,
        url: '/unit-amenities/outdoor-space/balcony-terrace',
        label: 'Balcony/Terrace',
      },
    ],
    _status: 'published',
  },
  // Private Garden
  {
    title: 'Private Garden',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'private-garden',
    slugLock: true,
    parent: 235,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4425',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4426',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b4427',
        doc: 237,
        url: '/unit-amenities/outdoor-space/private-garden',
        label: 'Private Garden',
      },
    ],
    _status: 'published',
  },
  // Outdoor Seating Area
  {
    title: 'Outdoor Seating Area',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'outdoor-seating-area',
    slugLock: true,
    parent: 235,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4428',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4429',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b442a',
        doc: 238,
        url: '/unit-amenities/outdoor-space/outdoor-seating-area',
        label: 'Outdoor Seating Area',
      },
    ],
    _status: 'published',
  },
  // Views
  {
    title: 'Views',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'views',
    slugLock: true,
    parent: 235,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b442b',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b442c',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b442d',
        doc: 239,
        url: '/unit-amenities/outdoor-space/views',
        label: 'Views',
      },
    ],
    _status: 'published',
  },
  // City View
  {
    title: 'City View',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'city-view',
    slugLock: true,
    parent: 239,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b442e',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b442f',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b4430',
        doc: 239,
        url: '/unit-amenities/outdoor-space/views',
        label: 'Views',
      },
      {
        id: '67b0b8899a1e4304421b4431',
        doc: 240,
        url: '/unit-amenities/outdoor-space/views/city-view',
        label: 'City View',
      },
    ],
    _status: 'published',
  },
  // Community View
  {
    title: 'Community View',
    isPremium: false,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'community-view',
    slugLock: true,
    parent: 239,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4432',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4433',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b4434',
        doc: 239,
        url: '/unit-amenities/outdoor-space/views',
        label: 'Views',
      },
      {
        id: '67b0b8899a1e4304421b4435',
        doc: 241,
        url: '/unit-amenities/outdoor-space/views/community-view',
        label: 'Community View',
      },
    ],
    _status: 'published',
  },
  // Park View
  {
    title: 'Park View',
    isPremium: true,
    description: null,
    image: null,
    relatedDocs: [],
    meta: {
      title: null,
      image: null,
      description: null,
    },
    noindex: null,
    authors: [],
    populatedAuthors: [],
    publishedAt: '2025-02-15T15:53:45.972Z',
    slug: 'park-view',
    slugLock: true,
    parent: 239,
    breadcrumbs: [
      {
        id: '67b0b8899a1e4304421b4436',
        doc: 200,
        url: '/unit-amenities',
        label: 'Unit Amenities',
      },
      {
        id: '67b0b8899a1e4304421b4437',
        doc: 235,
        url: '/unit-amenities/outdoor-space',
        label: 'Outdoor Space',
      },
      {
        id: '67b0b8899a1e4304421b4438',
        doc: 239,
        url: '/unit-amenities/outdoor-space/views',
        label: 'Views',
      },
      {
        id: '67b0b8899a1e4304421b4439',
        doc: 242,
        url: '/unit-amenities/outdoor-space/views/park-view',
        label: 'Park View',
      },
    ],
    _status: 'published',
  },
]
